### ISSUE TITLE
Null binding when using reactive wrappers as arguments

### ISSUE THREAD

**Issue by MiracleWisp** [spring-projects/spring-data-r2dbc#693] opened 2021-12-07 15:00 UTC
For custom methods in repositories I have null bindings when use reactive wrappers as arguments.

I have entity:

```
@Table("services")
public class ServiceOffering {
    @Id
    private UUID id;
    private String name;
    private String about;
    private double price;
    private int duration;
    private boolean approveRequired;
    private UUID specialistId;
}
```

And repository: 
```
public interface ServiceOfferingRepository extends ReactiveCrudRepository<ServiceOffering, UUID> {
    Flux<ServiceOffering> findBySpecialistId(Mono<UUID> specialistId);
    Flux<ServiceOffering> findByName(Mono<String> name);
}
```

When I execute one of two custom methods I get the following in logs:
`Bind parameter [0] to null, type: java.lang.String` or `Bind parameter [0] to null, type: java.util.String`

Default method `Mono<T> findById(Publisher<ID> id)` works as it should 

I use PostgreSQL as my Database
Spring boot version: 2.6.1

**Comment by mp911de** [comment] 2021-12-08 09:00
Generally, `Mono.empty()` translates to `null` while emission of a value binds the emitted value to the statement. This is also indicated by the log output.

Right now, I do not understand the problem. By providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem, we could look into what you want to achieve vs. what is happening.

**Comment by spring-projects-issues** [comment] 2021-12-15 09:02
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-12-22 09:02
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-12-22 09:02 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
