### ISSUE TITLE
R2dbc H2 issue when using inMemory database

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-data-r2dbc#269] opened 2020-01-05 05:40 UTC
I was trying to taste R2dbc and using Embedded H2 like:

```java
public ConnectionFactory connectionFactory() {
        //ConnectionFactory factory = ConnectionFactories.get("r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE");
        return new H2ConnectionFactory(
                H2ConnectionConfiguration.builder()
                        //.inMemory("testdb")
                        .file("./testdb")
                        .username("user")
                        .password("password").build()
        );
    }

```

And I defined a bean to create tables and init data. 

```java
@Bean
    public ConnectionFactoryInitializer initializer(ConnectionFactory connectionFactory) {

        ConnectionFactoryInitializer initializer = new ConnectionFactoryInitializer();
        initializer.setConnectionFactory(connectionFactory);

        CompositeDatabasePopulator populator = new CompositeDatabasePopulator();
        populator.addPopulators(new ResourceDatabasePopulator(new ClassPathResource("schema.sql")));
        populator.addPopulators(new ResourceDatabasePopulator(new ClassPathResource("data.sql")));
        initializer.setDatabasePopulator(populator);

        return initializer;
    }
```

And I also defined another Component to set up data by java codes.

```java

@Component
@Slf4j
class DataInitializer {

    private final DatabaseClient databaseClient;

    public DataInitializer(DatabaseClient databaseClient) {
        this.databaseClient = databaseClient;
    }

    @EventListener(value = ContextRefreshedEvent.class)
    public void init() {
        log.info("start data initialization  ...");
        this.databaseClient.insert()
            .into("posts")
            //.nullValue("id", Integer.class)
            .value("title", "First post title")
            .value("content", "Content of my first post")
            .map((r, m) -> r.get("id", Integer.class))
            .all()
            .log()
            .thenMany(
                this.databaseClient.select()
                    .from("posts")
                    .orderBy(Sort.by(desc("id")))
                    .as(Post.class)
                    .fetch()
                    .all()
                    .log()
            )
            .subscribe(null, null, () -> log.info("initialization done..."));
    }

}
```

If use `.inMemory("testdb")` in the `ConnectionFactory` bean definition, when the Spring `ApplicationContext` is initialized, it will fail because of **can not find table `POSTS`** when initializing `DataInitializer`. From the startup logging, `ConnectionFactoryInitializer` is initialized successfully, and table **POSTS** is created and data is inserted as expected by executing the schema.sql and data.sql. 

But switching to use `.file("./testdb")`, it worked.

The complete code is [here](https://github.com/hantsy/spring-reactive-sample/blob/master/data-r2dbc/).

**Comment by mp911de** [comment] 2020-01-05 10:02
The issue is related to H2‘s behavior to close the database when the last connection gets closed. Please configure the DB_CLOSE_DELAY=-1 option so H2 retains the database. Alternatively, use the H2ConnextionFactory.inMemory(...) factory method to create a Closeable connection factory that does not depend on the in-use connection count.

**Comment by hantsy** [comment] 2020-01-05 11:15
@mp911de Thanks.  
But by default, when I created the ConnectionFactory by ` H2ConnectionConfiguration.builder().inMemory("testdb")`, it is possible to add a default options( `DB_CLOSE_DELAY=-1`) to overcome this barrier?

**Comment by mp911de** [comment] 2020-01-05 11:29
That is rather a question for the H2 project as we’re just forwarding existing functionality. Please file a ticket in the H2 project to discuss that requirement. /cc @katzyn. 

Closing that issue here as it is not related to Spring Data R2DBC.

**Closed** 2020-01-05 11:29 UTC
Labels: for: stackoverflow, status: invalid

**Comment by katzyn** [comment] 2020-01-05 12:02
What do you want from H2? H2 already has `DB_CLOSE_DELAY` option, it should be explicitly specified by the end user when necessary and all wrappers on top of H2 should have possibility to pass this option and all other options to H2. R2DBC-H2 has [`H2ConnectionConfiguration.Builder.option(String)`](https://github.com/r2dbc/r2dbc-h2/blob/4d817c68468d665119cc066305f01f2df12313bc/src/main/java/io/r2dbc/h2/H2ConnectionConfiguration.java#L159-L168) method for this purpose. Perhaps documentation of [`H2ConnectionConfiguration.Builder.inMemory(String)`](https://github.com/r2dbc/r2dbc-h2/blob/4d817c68468d665119cc066305f01f2df12313bc/src/main/java/io/r2dbc/h2/H2ConnectionConfiguration.java#L126-L134) method could suggest to use the `option(String)` method with appropriate argument when application needs to keep the in-memory database alive even without connections.

**Comment by mp911de** [comment] 2020-01-05 13:01
There's probably a reason for why `DB_CLOSE_DELAY` isn't preconfigured when using the in-memory protocol of H2. It makes sense to update the documentation to hint folks towards the `DB_CLOSE_DELAY` option.

**Comment by katzyn** [comment] 2020-01-05 14:13
Yes, there is a reason: memory leak **by default** is a terrible design practice.
