### ISSUE TITLE
Add support for simple type projections

### ISSUE THREAD

**Issue by rj-hwang** [spring-projects/spring-data-r2dbc#41] opened 2018-12-28 09:22 UTC
I'm using spring-data-r2dbc-1.0.0.M1 with r2dbc-postgresql-1.0.0.M6. See below code, failed to select single field value. 

Code : 

```
public class Dream {
  @Id private Integer id;
  private String name;
  ...
}
public interface DreamRepository extends ReactiveCrudRepository<Dream, Integer> {
  @Query("select name from dream")
  Flux<String> findAllName();
}
```

Error message : 

```
org.springframework.data.mapping.MappingException: Couldn't find PersistentEntity for type class java.lang.String!

  at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:79)
  at org.springframework.data.r2dbc.function.DefaultReactiveDataAccessStrategy.getRequiredPersistentEntity(DefaultReactiveDataAccessStrategy.java:242)
  at org.springframework.data.r2dbc.function.DefaultReactiveDataAccessStrategy.getRowMapper(DefaultReactiveDataAccessStrategy.java:228)
  at org.springframework.data.r2dbc.function.DefaultDatabaseClient$DefaultTypedExecuteSpec.<init>(DefaultDatabaseClient.java:476)
  at org.springframework.data.r2dbc.function.DefaultDatabaseClient.createTypedExecuteSpec(DefaultDatabaseClient.java:223)
  at org.springframework.data.r2dbc.function.DefaultDatabaseClient$DefaultGenericExecuteSpec.as(DefaultDatabaseClient.java:408)
  at org.springframework.data.r2dbc.repository.query.AbstractR2dbcQuery.execute(AbstractR2dbcQuery.java:106)
  at org.springframework.data.r2dbc.repository.query.AbstractR2dbcQuery.execute(AbstractR2dbcQuery.java:84)
  at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:605)
  ...
  at com.sun.proxy.$Proxy38.findAllName(Unknown Source)
  at tech.simter.start.r2dbc.spring.dao.FindAllNameMethodImplTest.test(FindAllNameMethodImplTest.java:40)
  ...
```

My unit test code is [FindAllNameMethodImplTest.java](https://github.com/start-java/start-r2dbc/blob/master/src/test/java/tech/simter/start/r2dbc/spring/dao/FindAllNameMethodImplTest.java#L40)

**Comment by rj-hwang** [comment] 2018-12-28 12:12
Hope to realize it soon.

**Comment by mp911de** [comment] 2019-02-21 14:59
I revisited the topic and realized that we have support for DTO and interface projections. The missing bit is simple type projection (selecting plain `String` and such).

In Cassandra, we have solved the issue by registering `Converter`s from `Row` to the desired type `T`. We should provide the same for Spring Data R2DBC (see https://github.com/spring-projects/spring-data-cassandra/blob/e6b5c5e7a2af5c020526e6d998d5950b74163937/spring-data-cassandra/src/main/java/org/springframework/data/cassandra/core/convert/CassandraConverters.java#L57-L65 as reference). `EntityRowMapper` is currently being refactored via #61 so the scope of this ticket is just providing the necessary converters. Integration can happen once #61 is merged.

**Comment by uaihebert** [comment] 2019-02-21 17:37
hello @mp911de 

I have added something really close to the cassandra solution.

I still new in this project, so I just submitted a simple class so that you can point me the correct direction. once I get on tracks I will add the tests.

I got a few questions:

1. how should we convert the data? I used the same converter API. but the row from casandra is different than the row that we got in the project. 
1. how should the cast e effectively done? right now I am doing simples java casts like: `(Date) row.get(0)`. Should I convert to String and parse it later? I just need some reference, I could not find anything related.

**Comment by mp911de** [comment] 2019-02-22 08:42
Thanks a lot for getting involved into this ticket. Here are the answers for your questions:

1. We should use the typed R2DBC API, `row.get(0, LocalDate.class)` instead of the untyped one (`row.get(0)`) so the driver can provide native types and we do not require downcasting.
2. See 1.
3. Why had you to compile the dependencies? The `pom.xml` points to our snapshot repositories:
```
	<repositories>
		<repository>
			<id>spring-libs-snapshot</id>
			<url>https://repo.spring.io/libs-snapshot</url>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>spring-plugins-snapshot</id>
			<url>https://repo.spring.io/plugins-snapshot</url>
		</pluginRepository>
	</pluginRepositories>
```
If downloading from repo.spring.io does not work, then we should investigate why this is and fix the cause. Can you provide some more detail information (e.g. compile error message) so we can trace the issue?

**Comment by uaihebert** [comment] 2019-02-22 11:40
I just updated the PR.

well, it was saying that some dependencies were not found.

my clone history to make a successful build was like this:
![image](https://user-images.githubusercontent.com/2014377/53240420-f4204900-369e-11e9-9e54-7b2224cd2e09.png)

**Comment by uaihebert** [comment] 2019-02-22 12:03
Regarding the installation, I found the problems. 

My default maven was not a recent one. 

I did a small test here, I ran the openjdk:8-alpine machine and I was able to install all the dependencies. 

Thank you

**Comment by mp911de** [comment] 2019-02-22 13:41
On a related note: Please do not attach images with code/log/debug output as we cannot search for text in images.

**Closed** 2019-03-10 10:36 UTC
Labels: status: ideal-for-contribution, type: enhancement
