### ISSUE TITLE
Does @Query support CoroutineCrudRepository?

### ISSUE THREAD

**Issue by kev1n11** [spring-projects/spring-data-r2dbc#322] opened 2020-03-19 19:15 UTC
Is `@Query` supported for `CoroutineCrudRepository`? I'd guess yes because a bean was provided for the interface.

In the process of converting our project from `Reactor` to `Coroutines`, I've bumped into this exception:
```
Invalid parameter index! You seem to have declared too little query method parameters!
```

Our code was pretty much just
```
import org.springframework.data.r2dbc.repository.Query
import org.springframework.data.repository.kotlin.CoroutineCrudRepository

interface CoFooRepository : CoroutineCrudRepository<Foo, UUID> {
    @Query("SELECT * FROM foo WHERE x = :x AND y = :y")
    suspend fun findByXandY(x: String, y: Int): Foo?
}
```

**Comment by mp911de** [comment] 2020-03-19 20:20
This is a duplicate of #321.

**Closed** 2020-03-19 20:20 UTC
Labels: status: duplicate
