### ISSUE TITLE
r2dbc nested entity mapping

### ISSUE THREAD

**Issue by alim-zanibekov** [spring-projects/spring-data-r2dbc#749] opened 2022-03-31 15:22 UTC
Hello, I am using Spring Data R2DBC and I found that the mapping "feature" that I used for one-to-one connections stopped working.

For example 
```sql
create table users (id uuid not null primary key, username varchar(50) not null);
create table users_descriptions (user_id uuid not null primary key, name varchar(100) not null, phone varchar(13));
```
Entities
```kotlin
@Table("users")
data class UserEntity(val username: String, @Id val id: UUID = UUID.randomUUID())
@Table("users_descriptions")
data class UserDescriptionEntity(val name: String, val phone: String, @Id val userId: UUID)

data class UserWithDescriptionEntity(val username: String, val description: UserDescriptionEntity, val id: UUID)
```
Repo
```kotlin
@Repository
interface UserRepository: ReactiveCrudRepository<UserEntity, UUID> {
    @Query("SELECT u.*, ud.user_id as description_user_id, ud.name as description_name, " +
    "ud.phone as description_phone LEFT OUTER JOIN users_descriptions ud on ud.user_id = u.id")
    fun <T> findAllExtended(type: Class<T>): Flux<T>
}
```
Usage
```kotlin
userRepository.findAll() -> Flux<UserEntity>
userRepository.findAllExtended(UserWithDescriptionEntity::class.java) -> Flux<UserWithDescriptionEntity>
```

After [this](https://github.com/spring-projects/spring-data-r2dbc/commit/0ad751ec5cf9385099c0df3c11e179adcf92baff#diff-548a14a18f923aa008523ca0925f1652e12405fbe74db4bc6006baeead4ff48bL174) commit automatic mapping nested entity in that way stopped working.
As far as I understand, the readEntityFrom function takes the current field from the parent Entity as a prefix and further searches by Row using this prefix for the fields of the nested Entity, but now this function is not called if name of Entity field is not found in the metadata

I already found the workaround - just add something like this to the sql select statement `true as description`, but maybe it should work differently?

**Comment by mp911de** [comment] 2022-04-01 06:52
Nested entities were never intended to work because we do not yet have proper fetching strategies in place. We are working towards a solution, but for the time being, closing this one.

**Comment by mp911de** [comment] 2022-04-01 06:52
Duplicate of #695

**Closed as completed by mp911de** 2022-04-01 06:52 UTC
Labels: status: duplicate

**Comment by frreynal** [comment] 2024-10-19 13:31
same error here, any updates ?
