### ISSUE TITLE
Array fields not getting written

### ISSUE THREAD

**Issue by nishant-1984** [spring-projects/spring-data-r2dbc#156] opened 2019-07-31 18:06 UTC
I have a class model:

@Table("creation_tags")
data class CreationTags(
    @Id
    @Column("id") val id: Int?,
    @Column("segment") val segment: String?,
    @Column("star_tags") val starTags: Array<String>?,
    @Column("parent_tags") val parentTags: Array<String>?,
    @Column("sub_tags") val subTags: Array<String>?,
    @Column("occupations") val occupations: Array<String>?
)

only simple type String field segment is getting inserted.

Insert Script:

fun add1(creationTags: CreationTags): Mono<Void> {
        log.info("[CREATION_TAGS][${creationTags.segment}] Adding new segment {}", creationTags)

        return client.insert().into("creation_tags")
            .value("segment", creationTags.segment.toString())
            .value("star_tags", creationTags.starTags!!)
            .value("parent_tags", creationTags.parentTags!!)
            .value("sub_tags", creationTags.subTags!!)
            .value("occupations", creationTags.occupations!!).then()
    }

Also tried using clause with passing actual object it doesn't save it.

Inserted row:

11	test_segment9	null null null null null

**Comment by mp911de** [comment] 2019-08-01 06:37
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by mp911de** [comment] 2019-09-05 10:19
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2019-09-05 10:19 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage
