### ISSUE TITLE
Using Spring Data R2DBC with Functional Bean DSL?

### ISSUE THREAD

**Issue by peterfigure** [spring-projects/spring-data-r2dbc#378] opened 2020-06-01 20:18 UTC
In other words, using without the help of `AbstractR2dbcConfiguration` - I suppose the way is to manually define the beans within `AbstractR2dbcConfiguration` using the bean DSL but a cursory glance shows that some of them are dependent on a reference to the `ApplicationContext` which doesn't appear to be readily available?

**Comment by mp911de** [comment] 2020-06-08 14:42
It's possible to register a `DatabaseClient` bean by providing a `ConnectionFactory` object through `DatabaseClient.create(connectionFactory)`. This way of creating the client registers with the typical defaults for the bean. Obviously, `DatabaseClient` is an interface therefore you need a proper object factory.

The links to the application context stem from further integration (e.g. SpEL support that is able to refer to Spring beans) or customization of individual beans.

Happy to continue the discussion over a bit of code that shows difficulties with the bean registration.

**Comment by peterfigure** [comment] 2020-06-08 16:56
Thank you @mp911de - the bean definition went fairly smoothly but having a problem with Repositories no longer being generated in my integration tests (still works fine running the main Application)

```
@Configuration <=== received warning from IntelliJ about this being on a "final class"
@EnableR2dbcRepositories(basePackageClasses = [EscrowReactiveRepository::class])
object R2DBCConfigurationDSL: KLogging() {

    private val customConverters = listOf(
        AssetStateTypeReadingConverter(),
        AssetStateTypeWritingConverter()
    )

    private fun getDialect(connectionFactory: ConnectionFactory): R2dbcDialect {
        return DialectResolver.getDialect(connectionFactory)
    }

    val beans = beans {
        logger.info("Creating R2DBC beans using Functional DSL")

        bean<DatabaseClient>("databaseClient") { // TODO only a single name is supported through functional DSL?
            val projectionFactory = SpelAwareProxyProjectionFactory() // TODO do we need to set beanFactory and classloader properties?
            DatabaseClient.builder() //
                .connectionFactory(ref<ConnectionFactory>()) //
                .dataAccessStrategy(ref<ReactiveDataAccessStrategy>()) //
                .exceptionTranslator(ref<R2dbcExceptionTranslator>()) //
                .projectionFactory(projectionFactory) //
                .build()
        }
        
        bean<DatabaseClient>("r2dbcDatabaseClient") {
            ref<DatabaseClient>("databaseClient")
        }

        bean<R2dbcMappingContext>() {
            val context = R2dbcMappingContext((NamingStrategy.INSTANCE))
            context.setSimpleTypeHolder(ref<R2dbcCustomConversions>().simpleTypeHolder)
            context
        }

        bean<ReactiveDataAccessStrategy>("reactiveDataAccessStrategy") {
            val converter = MappingR2dbcConverter(ref<R2dbcMappingContext>(), ref<R2dbcCustomConversions>())
            DefaultReactiveDataAccessStrategy(getDialect(ref<ConnectionFactory>()), converter)
        }

        bean<R2dbcCustomConversions>() {
            R2dbcCustomConversions(ref<StoreConversions>(), customConverters)
        }

        bean<StoreConversions>() { // <===== had to make this a bean as it references connectionFactory
            val dialect = getDialect(ref<ConnectionFactory>())
            val converters: MutableList<Any> = ArrayList(dialect.converters)
            converters.addAll(R2dbcCustomConversions.STORE_CONVERTERS)
            StoreConversions.of(dialect.simpleTypeHolder, converters)
        }

        bean<R2dbcExceptionTranslator> {
            R2dbcExceptionSubclassTranslator()
        }
    }
}
```

I've also tried moving the annotations (one or both) to my `ApplicationContextInitializer` implementation which also didn't work but once I moved them both to every integration test it worked, unfortunately, this is not ideal.
Previously my integration tests worked when these two annotations were only on my `AbstractR2dbcConfiguration` extended class, which is a much better situation. 

When it doesn't work, I do not see these expected logs:

```
2020-06-08 16:23:53.499  INFO 10843 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data R2DBC repositories in DEFAULT mode.
2020-06-08 16:23:53.561  INFO 10843 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 59ms. Found 3 R2DBC repository interfaces.
```

**Comment by mp911de** [comment] 2020-06-09 10:10
Paging @sdeleuze. Do you have a reproducer? I'm not entirely familiar with the functional bean definition syntax in Kotlin so having a minimal runnable project would be helpful.

**Comment by peterfigure** [comment] 2020-06-09 15:06
I don't but I'll see if I can put one together

**Comment by nefilim** [comment] 2020-06-09 17:03
here: https://github.com/nefilim/spring-functional-dsl

**Comment by peterfigure** [comment] 2020-06-09 17:04
minimal project here: https://github.com/nefilim/spring-functional-dsl

**Comment by sdeleuze** [comment] 2020-06-11 08:57
Explore how `ImportBeanDefinitionRegistrar` can apply or be translated to functional bean registration is a topic I have not yet explored in [Spring Fu](https://github.com/spring-projects-experimental/spring-fu), but @dsyer or @aclement have worked on that as part of [spring-init](https://github.com/spring-projects-experimental/spring-init/) which has been recently upgraded to Spring Boot 2.3.0.

You can study R2DBC part of https://repo.spring.io/snapshot/org/springframework/experimental/spring-boot-autoconfigure/2.3.0.BUILD-SNAPSHOT/spring-boot-autoconfigure-2.3.0.BUILD-20200527.144954-2-func-sources.jar to check how it is used, and maybe use directly `org.springframework.experimental:spring-boot-autoconfigure:2.3.0.BUILD-SNAPSHOT` with `func` classifier to see if that work.

@mp911de @christophstrobl Notice this is something very interesting to explore since we are likely going to need that to reach next level of our GraalVM native support, see https://github.com/spring-projects-experimental/spring-graalvm-native/issues/164 for more context.

**Comment by mp911de** [comment] 2020-07-14 13:52
Closing this ticket here since this topic has moved into Spring Fu.

**Closed by mp911de** 2020-07-14 13:52 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage
