### ISSUE TITLE
support for mysql

### ISSUE THREAD

**Issue by skyding1212** [spring-projects/spring-data-r2dbc#499] opened 2020-11-13 10:15 UTC
support for mysql database with r2dbc (spring data r2dbc)

**Comment by mp911de** [comment] 2020-11-14 17:13
Duplicate of #75. Anything specific you're missing?

**Comment by mp911de** [comment] 2020-11-23 10:58
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2020-11-23 10:58 UTC
Labels: status: duplicate
