### ISSUE TITLE
Persistence custom enum value to database

### ISSUE THREAD

**Issue by rj-hwang** [spring-projects/spring-data-r2dbc#254] opened 2019-12-09 10:47 UTC
```
enum class Status(val dbValue: Short) {
  A(1), B(2)
}

data class User(
  @Id val id: Int? = null
  val status: Status,
  ...
)

interface UserRepository : R2dbcRepository<User, Int>
```

How to persistene the enum `dbValue` to database when persistence `User` with spring-data-r2dbc?

By now spring-data-r2dbc repository peisistence status value with the enum name string, such as 'A' and 'B'.

**Comment by mp911de** [comment] 2019-12-09 11:25
Using custom converters should do the job:

```
	enum MyEnumToIntegerConverter implements Converter<MyEnum, Integer> {

		INSTANCE;

		@Override
		public Integer convert(MyEnum myEnum) {
			return myEnum.ordinal();
		}
	}

	enum IntegerToMyEnumConverter implements Converter<Integer,MyEnum> {

		INSTANCE;

		@Override
		public MyEnum convert(Integer value) {
			return MyEnum.values()[value];
		}
	}
```

Alternatively, you can use the `ConverterBuilder` API:

```
		Set<GenericConverter> converters = ConverterBuilder
				.writing(MyEnum.class, Integer.class, myEnum -> {
					return myEnum.ordinal();
				}).andReading(integer -> MyEnum.values()[integer]).getConverters();
```

Make sure to register these with `R2dbcCustomConversions`.

**Comment by rj-hwang** [comment] 2019-12-10 01:06
Thanks. That's working for me.

But I found `R2dbcCustomConversions` only can register global converters follow [this guide](https://docs.spring.io/spring-data/r2dbc/docs/1.0.x/reference/html/#mapping.configuration):

```
@Configuration
public class MyAppConfig extends AbstractR2dbcConfiguration {
  @Bean
  @Override
  public R2dbcCustomConversions r2dbcCustomConversions() {
    List<Converter<?, ?>> customConverters = ...;
    return new R2dbcCustomConversions(getStoreConversions(), customConverters );
  }
  ...
}
```

Does spring-data-r2dbc support any similar way to register a entity-scop converter like the JPA `javax.persistence.Convert` annotation does:

```

@Entity
data class User(
  @get:Convert(converter = StatusConverter::class)
  val status: Status,
  ...
)
```

**Comment by mp911de** [comment] 2019-12-10 15:51
No, Spring Data does not support property-level converters. Spring Data's converters are one-way converter types. JPA's converters are two-way converters where write and read conversions are available from within a single type.

You might want to add your example to the ticket [DATACMNS-1036](https://jira.spring.io/browse/DATACMNS-1036).

Closing this ticket as the issue is solved.

**Closed by mp911de** 2019-12-10 15:51 UTC
Labels: type: documentation
