### ISSUE TITLE
Failed to update table [xxxx]  Row with id [12] does not exist when no data was updated

### ISSUE THREAD

**Issue by bigdoubletao** [spring-projects/spring-data-r2dbc#522] opened 2021-01-06 09:41 UTC
for example 
user:{"id":12,"name":"zt"}
save
user:{"id":12,"name":"zt"}
Failed to update table [xxxx]  Row with id [12] does not exist when no data was updated

**Comment by mp911de** [comment] 2021-01-06 10:13
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by spring-issuemaster** [comment] 2021-01-13 10:14
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by mp911de** [comment] 2021-04-06 11:48
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2021-04-06 11:48 UTC
