### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by rezaep** [spring-projects/spring-data-r2dbc#337] opened 2020-04-08 07:37 UTC
It's my first experience with spring-data-r2dbc, so I'm not sure if it's a bug or I'm missing something.

### Description
I'm using `spring-data-r2dbc` with `Kotlin` and `WebFlux`.

`build.gradle.kts`:
```
plugins {
    id("org.springframework.boot") version "2.3.0.M4"
    id("io.spring.dependency-management") version "1.0.9.RELEASE"
    kotlin("jvm") version "1.3.71"
    kotlin("plugin.spring") version "1.3.71"
}
...
dependencies {
    implementation("org.springframework.boot:spring-boot-starter-cache")
    implementation("org.springframework.boot:spring-boot-starter-data-r2dbc")
    implementation("org.springframework.boot:spring-boot-starter-webflux")
    implementation("org.springframework.boot:spring-boot-starter-validation")
...
}
```
Assuming I have a simple Repository:

`CityRepository`:
```Kotlin
interface CityRepository : ReactiveCrudRepository<City, Long> {
    fun findByNameContainingIgnoreCase(name: String, page: Pageable): Flux<City>
}
```

When I call the `findByNameContainingIgnoreCase` with the following parameters:
```Kotlin
val page = PageRequest.of(0, 10, Sort.by(Sort.Direction.ASC, "name"))
return cityRepository.findByNameContainingIgnoreCase(name, page)
                .map { convertToModel(it) }
```
the generated log is:
```
2020-04-08 12:02:17.777 DEBUG 9184 --- [ctor-http-nio-2] o.s.d.r2dbc.core.DefaultDatabaseClient   : Executing SQL statement [SELECT city.city_id, city.name, city.state, city.country, city.lat, city.lng FROM city WHERE UPPER(city.name) LIKE UPPER($1) ORDER BY name ASC]
2020-04-08 12:02:17.778 DEBUG 9184 --- [ctor-http-nio-2] o.s.d.r2dbc.core.NamedParameterExpander  : Expanding SQL statement [SELECT city.city_id, city.name, city.state, city.country, city.lat, city.lng FROM city WHERE UPPER(city.name) LIKE UPPER($1) ORDER BY name ASC] to [SELECT city.city_id, city.name, city.state, city.country, city.lat, city.lng FROM city WHERE UPPER(city.name) LIKE UPPER($1) ORDER BY name ASC]
```
According to the log, we can see only the sort is used and the query returns all rows matched to the `where` clause ordered by name.

But when I change the method in the repository to `findTop10ByNameContainingIgnoreCase` the log changes to:

```
2020-04-08 12:07:32.121 DEBUG 13020 --- [ctor-http-nio-2] o.s.d.r2dbc.core.DefaultDatabaseClient   : Executing SQL statement [SELECT city.city_id, city.name, city.state, city.country, city.lat, city.lng FROM city WHERE UPPER(city.name) LIKE UPPER($1) ORDER BY name ASC LIMIT 10]
2020-04-08 12:07:32.121 DEBUG 13020 --- [ctor-http-nio-2] o.s.d.r2dbc.core.NamedParameterExpander  : Expanding SQL statement [SELECT city.city_id, city.name, city.state, city.country, city.lat, city.lng FROM city WHERE UPPER(city.name) LIKE UPPER($1) ORDER BY name ASC LIMIT 10] to [SELECT city.city_id, city.name, city.state, city.country, city.lat, city.lng FROM city WHERE UPPER(city.name) LIKE UPPER($1) ORDER BY name ASC LIMIT 10]
```

which adds the `limit` to the query.

So, why passing `Pageable` to the query doesn't work for me? Am I missing something?

**Comment by mp911de** [comment] 2020-04-08 08:53
This is a duplicate of #335.

**Closed by mp911de** 2020-04-08 08:53 UTC
Labels: status: duplicate

**Comment by vladimirshin** [comment] 2021-05-19 13:05
What's the status on this issue?
