### ISSUE TITLE
ReactiveCrudRepository#save save not returning properly

### ISSUE THREAD

**Issue by tobq** [spring-projects/spring-data-r2dbc#528] opened 2021-01-15 12:01 UTC
Using `org.springframework.data.repository.reactive.ReactiveCrudRepository#save`, entities are being saved improperly.

For the entity:

```
@ToString
@Value class Entity {
    @Id
    UUID id;
    @CreatedDate
    Instant created;
}
```

The line `reactiveRepo.save(new Entity(null, null)).subscribe(System.out::println)` logs:
 
> Entity(id=9d79b1c5-8caf-4aa3-9d8f-8f2d1dd2bbd7, created=null)

The entity is actually saved to the database as expected; however, the saved entity returned by `save` has the  `null` value remaining in the `created` field - as opposed to the DBMS' default-generated value (`now()`).

This issue also persists after removing the `@CreatedDate` annotation.

If I call `findById` with the returned ID, I'm able to get the correct entity (with `Instant created` populated correctly).

---

Using `Spring boot 2.4.2`, `spring-boot-starter-data-r2dbc` and `r2dbc-postgresql`

**Comment by mp911de** [comment] 2021-01-15 14:59
R2DBC drivers don't return server-generated values by default. The only reliable generated value is the Id value that we can obtain from the driver. Anything else is highly database-specific.

That being said, everything works as expected and this ticket doesn't qualify as bug.

**Comment by tobq** [comment] 2021-01-15 18:03
@mp911de So, am I going to have to re-query the repository for the data just saved?

**Comment by mp911de** [comment] 2021-01-15 18:29
Yes, for now it's the only option. We have another ticket asking to hydrate the data model with values that are sent by Postgres (see spring-projects/spring-data-relational#1274)

**Comment by mp911de** [comment] 2021-01-18 13:03
Closing this ticket as a duplicate of spring-projects/spring-data-relational#1274.

**Closed by mp911de** 2021-01-18 13:03 UTC
Labels: status: feedback-provided, status: waiting-for-triage
