### ISSUE TITLE
RowsFetchSpec<T>.awaitOne() and RowsFetchSpec<T>.awaitFirst() should throw EmptyResultDataAccessException

### ISSUE THREAD

**Issue by pull-vert** [spring-projects/spring-data-r2dbc#103] opened 2019-04-27 08:40 UTC
Hi,
@sdeleuze 
Kotlin non-nullable extension functions `RowsFetchSpec<T>.awaitOne()` and `RowsFetchSpec<T>.awaitFirst()` throw `NoSuchElementException` with message 

```
No value received via onNext for awaitSingle
```

when no result is found, because they are based on `Publisher<T>.awaitSingle()` from kotlinx-coroutines.
I use `awaitOne()` in `findById` for example.

Maybe this Exception is too generic, it could be catched and throw a new Exception that extends `R2dbcException` instead (NoResultFound***Exception for example) ?

**Comment by mp911de** [comment] 2019-04-27 10:23
`awaitOne()` and `awaitFirst()` extensions are based on Coroutine extensions. This is an interesting scenario in the context of Spring and Coroutines. Typically, value mismatches are communicated with Spring's DAO exceptions (e.g. `EmptyResultDataAccessException` for a single result instead of returning `null`).

I'm currently not sure what the right thing to do is: Is it the technical aspect that rules here with `NoSuchElementException` or has Spring higher precedence.

**Comment by pull-vert** [comment] 2019-04-27 11:53
Thanks @mp911de for the clarification of this use case.
Let me add the unit test that made me open this issue, IMO this assertion doesn't looks good
```kotlin
@Test
fun `Verify findById returns no Unknown User`() = runBlockingTest {
    expectThrows<NoSuchElementException> { userRepository.findById("Unknown") }
                .message.isEqualTo("No value received via onNext for awaitSingle")
}
```

**Comment by mp911de** [comment] 2019-04-27 12:01
Thanks for adding context, I was missing how that code was going to be used. From that perspective, it would make sense to stay within the Spring DAO exception hierarchy as there is no application-side glue code to Coroutines (Don't think `runBlockingTest` counts as glue code).

**Comment by sdeleuze** [comment] 2019-05-14 08:29
I think the issue here is that `RowsFetchSpec` does not provide API where a single result is enforced, and I think the root cause is that `Mono` has been designed to be the only type for single/empty value and can't express any null-safety via its generic parameter by design, since it extends `Publisher` which does not accept `null`. On Coroutines side, we are able to express that difference, but we do it at Coroutines level that's why no Spring Data more meaningful extension is thrown.

If we consider Java API is fine like that, and if we think Spring Data exception like `EmptyResultDataAccessException` is relevant here, I think we can catch the `NoSuchElementException` and wrap it in a `EmptyResultDataAccessException` that extension will throw.

Any thoughts?

**Comment by pull-vert** [comment] 2019-05-15 20:22
That would solve this issue : throw ```EmptyResultDataAccessException``` and hide the technical ```NoSuchElementException``` from kotlinx-coroutines !

**Comment by mp911de** [comment] 2019-05-17 12:47
I'd argue there's no need for throwing `NoSuchElementException` in the first place. 

`awaitOne`/`awaitFirst` can use `awaitFirstOrNull()`. If the result is `null`, then the extension throws `EmptyResultDataAccessException`.

**Comment by mp911de** [comment] 2019-07-15 12:17
That's fixed now.

**Closed by mp911de** 2019-07-15 12:17 UTC
Labels: for: team-attention, type: bug
