### ISSUE TITLE
org.springframework.r2dbc.core.ColumnMapRowMapper.apply(Row, RowMetadata)

### ISSUE THREAD

**Issue by Stokoloshe** [spring-projects/spring-data-r2dbc#635] opened 2021-08-10 01:54 UTC
this method will cause data map error
if select column a\b\ c , the value will be ok,  if select column b\a\c, the value will not be ok, the value of b will be a's value

**Comment by mp911de** [comment] 2021-09-20 14:24
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by spring-projects-issues** [comment] 2021-09-27 14:28
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-10-04 14:28
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-10-04 14:28 UTC
Labels: status: feedback-reminder, status: waiting-for-triage
