### ISSUE TITLE
Reactive repository save method hangs with current build snapshot

### ISSUE THREAD

**Issue by nbabic298** [spring-projects/spring-data-r2dbc#58] opened 2019-02-05 17:01 UTC
I noticed today that calls to reactive repository `save` method hang indefinitely when `block` is called (for instance in tests, I'm using Postgre DB).

It worked few days ago, please see my example project and specifically try `R2dbcTestApplicationTest.testSave` method: https://github.com/nbabic298/basic-spring-r2dbc-postgre

I tried to dig into the source code for save but unfortunately couldn't find my way through.

**Comment by gregturn** [comment] 2019-02-05 17:19
Indeed, blocking is bad when using reactive programming. This is the exact scenario you can run into.

For testing, recommendation is to use Reactor's `StepVerifier`, which will properly subscribe and then execute all your asserts, etc.

See existing test suite for examples.

**Comment by mp911de** [comment] 2019-02-06 07:47
Thanks for the report and your example repo. Let me take a look.

**Comment by mp911de** [comment] 2019-02-06 14:07
The issue is caused by the Postgres driver. The following code hangs with 1.0.0 M6 but runs with 1.0.0.BUILD-SNAPSHOT.

```java
PostgresqlConnection connection = connectionFactory.create().block();
statements.forEach(it -> {

	System.out.println(it);
	connection.createStatement(it).execute().flatMap(r -> r.map((row, rowMetadata) -> row))
			.as(StepVerifier::create)
			.verifyComplete();
});
```

Due to SPI changes it's not possible to upgrade to the latest R2DBC driver snapshots with Spring Data R2DBC. Once R2DBC releases 1.0 M7 we will upgrade Spring Data with #54.

Closing as there's nothing more that we could do here.

**Closed by mp911de** 2019-02-06 14:07 UTC
Labels: type: bug
