### ISSUE TITLE
SQL executed only last one when Flux#concatMap nested Mono#flatMap 

### ISSUE THREAD

**Issue by lienide** [spring-projects/spring-data-r2dbc#604] opened 2021-06-13 04:23 UTC
- Question
Executed two sql to update `test` table but only last sql succeed, as below logging desc: 

> SQL1
2021-06-12 13:52:27.173 DEBUG 28977 --- [           main] io.r2dbc.pool.ConnectionPool             : Obtaining new connection from the driver
2021-06-12 13:52:27.393 DEBUG 28977 --- [actor-tcp-nio-2] o.s.r2dbc.core.DefaultDatabaseClient     : Executing SQL statement [UPDATE user SET age = :v where id = :id]
2021-06-12 13:52:27.418 DEBUG 28977 --- [actor-tcp-nio-2] io.r2dbc.pool.PooledConnection           : Releasing connection

> SQL2
2021-06-12 13:52:27.422 DEBUG 28977 --- [actor-tcp-nio-2] io.r2dbc.pool.ConnectionPool             : Obtaining new connection from the driver
2021-06-12 13:52:27.422 DEBUG 28977 --- [actor-tcp-nio-2] o.s.r2dbc.core.DefaultDatabaseClient     : Executing SQL statement [UPDATE user SET age = :v where id = :id]
2021-06-12 13:52:27.465 DEBUG 28977 --- [actor-tcp-nio-2] io.r2dbc.pool.PooledConnection           : Releasing connection

mysql data before update
```sql
mysql> select * from user\G
*************************** 1. row ***************************
  id: 1
name: 5
 age: 100
*************************** 2. row ***************************
  id: 0
name: 0
 age: 100
2 rows in set (0.00 sec)
```

mysql data after update
```sql
mysql> select * from user\G
*************************** 1. row ***************************
  id: 1
name: 5
 age: 100
*************************** 2. row ***************************
  id: 0
name: 0
 age: 0
2 rows in set (0.00 sec)

mysql>
```

- pom.xml
![image](https://user-images.githubusercontent.com/29501807/121774287-5e34c300-cbb4-11eb-8d1c-7df5590d9939.png)

- core code
```java
@Bean
public CommandLineRunner commandLineRunner(UserRepository userRepository) {
    return new CommandLineRunner() {
        @Override
        public void run(String... args) throws Exception {
            Flux.range(1, 10)
                    .map(i -> new User("t" + i, i % 2))
                    .groupBy(User::getAge)
                    .concatMap(groupFlux -> groupFlux.doOnNext(u -> System.out.println(u))
                            .map(User::getAge)
                            .map(BigDecimal::valueOf)
                            .reduce(BigDecimal::add)
                            .flatMap(v -> {
                                System.out.println("update user set age = " + v.intValue() + " where id = " + groupFlux.key());
                                return userRepository.consume(groupFlux.key(), v.intValue());
                            })
                    )
                    .subscribe()
                    ;

            TimeUnit.SECONDS.sleep(10);
        }
    };
}

public interface UserRepository extends ReactiveCrudRepository<User, Integer> {

    @Modifying
    @Query("UPDATE user SET age = :v where id = :id")
    Mono<Void> consume(Integer id, Integer v);
}
```

debug logging
```bash
2021-06-12 13:52:26.986 DEBUG 28977 --- [           main] ySourcesPropertyResolver$DefaultResolver : Found key 'spring.liveBeansView.mbeanDomain' in PropertySource 'systemProperties' with value of type String
2021-06-12 13:52:26.990  INFO 28977 --- [           main] org.example.Application                  : Started Application in 4.15 seconds (JVM running for 4.792)
2021-06-12 13:52:26.992  INFO 28977 --- [           main] o.s.b.a.ApplicationAvailabilityBean      : Application availability state LivenessState changed to CORRECT
User{id=null, name='t1', age=1}
User{id=null, name='t3', age=1}
User{id=null, name='t5', age=1}
User{id=null, name='t7', age=1}
User{id=null, name='t9', age=1}
update user set age = 5 where id = 1
2021-06-12 13:52:27.173 DEBUG 28977 --- [           main] io.r2dbc.pool.ConnectionPool             : Obtaining new connection from the driver
2021-06-12 13:52:27.393 DEBUG 28977 --- [actor-tcp-nio-2] o.s.r2dbc.core.DefaultDatabaseClient     : Executing SQL statement [UPDATE user SET age = :v where id = :id]
2021-06-12 13:52:27.418 DEBUG 28977 --- [actor-tcp-nio-2] io.r2dbc.pool.PooledConnection           : Releasing connection
User{id=null, name='t2', age=0}
User{id=null, name='t4', age=0}
User{id=null, name='t6', age=0}
User{id=null, name='t8', age=0}
User{id=null, name='t10', age=0}
update user set age = 0 where id = 0
2021-06-12 13:52:27.422 DEBUG 28977 --- [actor-tcp-nio-2] io.r2dbc.pool.ConnectionPool             : Obtaining new connection from the driver
2021-06-12 13:52:27.422 DEBUG 28977 --- [actor-tcp-nio-2] o.s.r2dbc.core.DefaultDatabaseClient     : Executing SQL statement [UPDATE user SET age = :v where id = :id]
2021-06-12 13:52:27.465 DEBUG 28977 --- [actor-tcp-nio-2] io.r2dbc.pool.PooledConnection           : Releasing connection
2021-06-12 13:52:37.198  INFO 28977 --- [           main] o.s.b.a.ApplicationAvailabilityBean      : Application availability state ReadinessState changed to ACCEPTING_TRAFFIC
```

Maybe i'm missing what?

Thanks check it!

**Comment by lienide** [comment] 2021-06-13 04:25
when i switch sql to SPEL in ReactiveCrudRepository impl it's work OK!

```java
@Modifying
@Query("UPDATE user SET name = :#{[1]} where id = :#{[0]}")
// @Query("UPDATE user SET name = :name where id = :id") // to bug fixed
Mono<Void> consume(Integer id, String name);
```

**Comment by lienide** [comment] 2021-06-13 04:32
query named type work ok just without @Modifying, and parameter binding by annotating the query method with @Modifying is not ok.

```java
public interface UserRepository extends ReactiveCrudRepository<User, Integer> {

    @Modifying
    // @Query("UPDATE user SET name = :#{[1]} where id = :#{[0]}")
    @Query("UPDATE user SET name = :name where id = :id") // WITH BUG: execute; bad SQL grammar [UPDATE user SET name = :name where id = :id]; nested exception is io.r2dbc.spi.R2dbcBadGrammarException: [1292] [22007] Truncated incorrect DOUBLE value: 'nnt3'
    Mono<Void> consume(Integer id, String name);

    @Modifying
    @Query("UPDATE user SET age = :age where id = :id") // WITH BUG: SQL executed normal according debug logging but non effect database store
    Mono<Void> consume(Integer id, Integer age);

    @Query("SELECT * FROM user where id = :id")
    Mono<User> findByIda(Integer id);
}
```

**Comment by mp911de** [comment] 2021-06-14 13:43
I'm not sure what you're trying to achieve. Having a test case that reproduces the issue within a test would be useful. As per your logs:

```
update user set age = 5 where id = 1

…

update user set age = 0 where id = 0
```

Looks pretty much what the data in your database looks like.

**Comment by spring-projects-issues** [comment] 2021-06-21 13:47
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-06-28 13:47
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-06-28 13:47 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
