### ISSUE TITLE
Can't use simple type projections in version 1.3.2

### ISSUE THREAD

**Issue by anuger** [spring-projects/spring-data-r2dbc#630] opened 2021-07-21 14:22 UTC
Code:
``` java
@Query("select friend_id from friend where account_id = :accountId")
    Flux<String> findFriendIdByAccountId(String accountId);
```
In version 1.2.9, it was successful. but after upgrading to 1.3.2, has exception:
```
org.springframework.data.mapping.MappingException: Couldn't find PersistentEntity for type class java.lang.String!
	at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:79)
	at org.springframework.data.relational.repository.query.DtoInstantiatingConverter.<init>(DtoInstantiatingConverter.java:61)
	at org.springframework.data.r2dbc.repository.query.R2dbcQueryExecution$ResultProcessingConverter.convert(R2dbcQueryExecution.java:112)
	at org.springframework.data.r2dbc.repository.query.R2dbcQueryExecution$ResultProcessingExecution.execute(R2dbcQueryExecution.java:64)
	at org.springframework.data.r2dbc.repository.query.AbstractR2dbcQuery.executeQuery(AbstractR2dbcQuery.java:125)
	at org.springframework.data.r2dbc.repository.query.AbstractR2dbcQuery.lambda$execute$0(AbstractR2dbcQuery.java:91)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:163)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
...
```
Did I miss any upgrade changes?

**Comment by mp911de** [comment] 2021-07-22 06:35
This is a duplicate of #612

**Closed by mp911de** 2021-07-22 06:35 UTC
Labels: status: duplicate
