### ISSUE TITLE
Null boolean value on generated countBy with where clause query

### ISSUE THREAD

**Issue by ben-dale** [spring-projects/spring-data-r2dbc#735] opened 2022-03-03 15:29 UTC
We recently tried to upgrade one of our projects from springboot 2.6.3 to 2.6.4 (upgrading spring-data-r2dbc:1.4.1 to spring-data-r2dbc:1.4.2), which introduced an interesting error that we believe stems from this project 🤔  

We have an interface:
```kotlin
interface XYZRepository : CoroutineCrudRepository<XYZ, UUID> {
    suspend fun countByAvailabilityTrue(): Int
}
```

We turned on logging using the r2dbc logging application properties to see what query was being generated:
```
logging.level.io.r2dbc.postgresql.QUERY=DEBUG
logging.level.io.r2dbc.postgresql.PARAM=DEBUG
```

Before upgrading to springboot 2.6.3 (spring-data-r2dbc:1.4.1):
```json
{"message":"Executing query: SELECT COUNT(xyz.user_id) FROM xyz WHERE xyz.availability = TRUE","status":"DEBUG"}
```

After upgrading to springboot 2.6.4 (spring-data-r2dbc:1.4.2):
```json
{"message":"Bind parameter [0] to null, type: java.lang.Boolean","status":"DEBUG"}
{"message":"Executing query: SELECT COUNT(xyz.user_id) FROM xyz WHERE xyz.availability = $1","status":"DEBUG"}
```

Notice after the upgrade, the boolean parameter is being forcibly set to `null`. 

We understand from the documentation [here](https://docs.spring.io/spring-data/r2dbc/docs/1.4.2/reference/html/#r2dbc.repositories.queries) and [here](https://docs.spring.io/spring-data/r2dbc/docs/1.4.2/reference/html/#r2dbc.repositories.queries) that our usage should be valid.

Apologies in advance if this is not the correct project to raise this issue in. Thanks!

**Comment by mp911de** [comment] 2022-03-04 07:26
This is a duplicate of #733. Care to upgrade to the latest snapshots of Spring Data R2DBC and retry to confirm that the bugfix works for you?

**Closed by mp911de** 2022-03-04 07:26 UTC
Labels: status: duplicate
