### ISSUE TITLE
Column not found

### ISSUE THREAD

**Issue by mctdi** [spring-projects/spring-data-r2dbc#149] opened 2019-07-16 15:43 UTC
I use spring boot, postgress and r2dbc.
I try to do a basic query to get user

Used recent version of libs

> implementation 'io.r2dbc:r2dbc-postgresql:1.0.0.M7'
>     compile 'io.r2dbc:r2dbc-pool:1.0.0.BUILD-SNAPSHOT'
>     implementation 'org.springframework.boot.experimental:spring-boot-starter-r2dbc:0.1.0.M1'
>     implementation 'org.springframework.boot.experimental:spring-boot-starter-data-r2dbc:0.1.0.BUILD-SNAPSHOT'

	
Code

        public interface UserRepository extends ReactiveCrudRepository<User, Integer> {
		@Query("SELECT * FROM user WHERE username = :username")
		public Mono<User> findByUsername(String username);
	}
	

	@Table
	public class User{

		@Id
		private Integer id;

		private String username;
		private String password;

		private boolean enabled;

		private String role;
		...
	}
	
	
	EnableDiscoveryClient
	@SpringBootApplication
	//@EnableR2dbcRepositories enable get same error
	public class GatewayServiceApplication {
		...
	}
	
	@Component
	public class ApplicationRunner implements CommandLineRunner{

                 @Autowired
                 private DatabaseClient client;

		@Autowired
		private UserRepository repository;

		@Override
		public void run(String... args) throws Exception {
			repository.findAll().subscribe(user-> System.out.println(user.getId() + " " + user.getUsername() + " " + user.getRole()));
		}

	}
	
	@Configuration
	@EnableR2dbcRepositories
	public class DatabaseConfig extends AbstractR2dbcConfiguration {

		@Override
		public ConnectionFactory connectionFactory() {
			return new PostgresqlConnectionFactory(
					PostgresqlConnectionConfiguration.builder()
							.host("localhost")
							.port(5432)
							.database("mermacon")
							.schema("lcn")
							.username("test")
							.password("test").build()
			);
		}
	}

	
When application start, I get
	
	

>  i.r.p.client.ReactorNettyClient          : Error: SEVERITY_LOCALIZED=ERROR, SEVERITY_NON_LOCALIZED=ERROR, CODE=42601, MESSAGE=syntax error at or near ".", POSITION=12, FILE=scan.l, LINE=1128, ROUTINE=scanner_yyerror

	 
	 If findByUsername method is called, i get
	

> i.r.p.client.ReactorNettyClient          : Error: SEVERITY_LOCALIZED=ERROR, SEVERITY_NON_LOCALIZED=ERROR, CODE=42703, MESSAGE=column "username" does not exist, POSITION=26, FILE=parse_relation.c, LINE=3194, ROUTINE=errorMissingColumn

In the ApplicationRunner class, if i add

 ```
client.execute("select * from lcm.user").fetch().all().subscribe(
                user-> System.out.println(user.keySet())
        );
```

I see columns of user table

[id, username, password, role]

So issue seem repository

**Comment by mp911de** [comment] 2019-08-15 10:24
Can you please include the database schema for a complete reproducible example?

**Comment by maslick** [comment] 2019-08-16 19:04
> Can you please include the database schema for a complete reproducible example?
Isn't the schema populated automatically when using ``spring.jpa.hibernate.ddl-auto=update``?

**Comment by schauder** [comment] 2019-08-19 05:29
@maslick No, because 
a) normally you wouldn't have Hibernate on the classpath when using r2dbc
b) you won't have Hibernate/JPA entities

**Comment by mp911de** [comment] 2019-09-02 14:42
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2019-09-02 14:42 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage

**Comment by Prilipko** [comment] 2020-04-20 18:27
Hi guys. I get the same issue. this is because of **user** table. 
For some reason driver did not take table name in quotes 
so postgressql could not perform
SELECT user.* FROM user
 [42601] syntax error at or near "."

**Comment by pecataToshev** [comment] 2020-05-08 15:47
Hi, I have same issue too
`
org.springframework.data.r2dbc.BadSqlGrammarException: executeMany; bad SQL grammar [SELECT user.id, user.username FROM user WHERE user.username = $1]; nested exception is io.r2dbc.postgresql.ExceptionFactory$PostgresqlBadGrammarException: [42601] syntax error at or near "." 
`
```
public interface DbUserRepository extends ReactiveCrudRepository<DbUser, Integer> {
  Mono<DbUser> findByUsername(String username);
}
```
```
@AllArgsConstructor
@Data
@NoArgsConstructor
@Table("user")
public class DbUser {

  @Id
  private Integer id;

  private String username;
}
```
```
                                     Table "public.user"
  Column  |          Type          | Collation | Nullable |             Default              
----------+------------------------+-----------+----------+----------------------------------
 id       | integer                |           | not null | generated by default as identity
 username | character varying(255) |           | not null | 

```

**Comment by mp911de** [comment] 2020-05-08 15:56
Which Postgres version is that? And how can I reproduce the issue?

**Comment by pecataToshev** [comment] 2020-05-08 16:14
Postgres 12.2
I only execute `dbUserRepository.findByUsername("username")` and it crashes

**Comment by pecataToshev** [comment] 2020-05-09 12:57
I've created [repo](https://github.com/pecataToshev/spring-data-r2dbc-postgresql-error). As you can see this problem appears only with postgre. H2 doesn't seem to have this problem. Also there is problem with generating `existsByUsername` method.

**Comment by mp911de** [comment] 2020-05-12 08:07
@pecataToshev `user` is a reserved Postgres keyword so you need to escape it. This applies also to String queries in `@Query`. You can enable identifier quotation on the mapping context through:

```
@Bean
public R2dbcMappingContext r2dbcMappingContext(Optional<NamingStrategy> namingStrategy,
		R2dbcCustomConversions r2dbcCustomConversions) {

	Assert.notNull(namingStrategy, "NamingStrategy must not be null!");

	R2dbcMappingContext context = new R2dbcMappingContext(namingStrategy
			.orElse(NamingStrategy.INSTANCE));
	context.setSimpleTypeHolder(r2dbcCustomConversions.getSimpleTypeHolder());
	context.setForceQuote(true);

	return context;
```

**Comment by pecataToshev** [comment] 2020-05-12 19:04
Thanks! Everything is ok now.
