### ISSUE TITLE
java.lang.IllegalStateException: Required property not found for class

### ISSUE THREAD

**Issue by cooperlyt** [spring-projects/spring-data-r2dbc#858] opened 2024-04-15 03:18 UTC
```kotlin
class SomeData(fieldOne: String, fieldTwo: String){
  private val combo: ComboClass = ComboClass(fieldOne, fieldTwo)

  fun getCombo() {
     return combo
  }
}

````
throw exception :  java.lang.IllegalStateException: Required property not found for class

but change to :

```kotlin
class SomeData(private val fieldOne: String, private val fieldTwo: String){
  private val combo: ComboClass = ComboClass(fieldOne, fieldTwo)

  fun getCombo() {
     return combo
  }
}
```
it's OK!  or fieldOne and fieldTwo have getter that is OK too!

**Comment by mp911de** [comment] 2024-04-15 07:47
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal yet complete sample](https://stackoverflow.com/help/mcve) that reproduces the problem.
You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by spring-projects-issues** [comment] 2024-04-22 07:48
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2024-04-29 07:48
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed as not planned by spring-projects-issues** 2024-04-29 07:48 UTC
