### ISSUE TITLE
Add support for routing connection factory similar to AbstractRoutingDataSource

### ISSUE THREAD

**Issue by dharezlak** [spring-projects/spring-data-r2dbc#273] opened 2020-01-09 20:45 UTC
It would be nice to have a reactive equivalent of the `AbstractRoutingDataSource` to address scenarios such as multi-tenant databases.

Would it be possible to implement this with currently available configuration plumbing?

**Comment by mp911de** [comment] 2020-01-10 10:14
That's in place with `org.springframework.data.r2dbc.connectionfactory.lookup.AbstractRoutingConnectionFactory`. Check out the [tests](https://github.com/spring-projects/spring-data-r2dbc/blob/7ec3d28b17ef4c4a6c77b355c777cccf9519cb10/src/test/java/org/springframework/data/r2dbc/connectionfactory/lookup/AbstractRoutingConnectionFactoryUnitTests.java#L39) on how to use it.

**Comment by mp911de** [comment] 2020-01-10 10:14
Duplicate of #98.

**Closed by mp911de** 2020-01-10 10:14 UTC
Labels: status: duplicate

**Comment by matusekma** [comment] 2023-07-27 07:13
Hi @mp911de ,
could this be documented or mentioned somewhere in the Spring documentation?
