### ISSUE TITLE
[2.7.2] Add Support for Kotlin Value Classes

### ISSUE THREAD

**Issue by rowi1de** [spring-projects/spring-data-r2dbc#779] opened 2022-08-25 15:20 UTC
- Issue from spring-data-commons https://github.com/spring-projects/spring-data-commons/issues/1947 https://github.com/spring-projects/spring-data-relational/issues/1093#issuecomment-972917101
- Spring + Dependencies 2.7.2 
```kotlin
@Repository
interface ValueRepository : CoroutineCrudRepository<DbValue UUID> {}

@Table("value")
class DbValue( val someValue: SomeValue )

@JvmInline
value class SomeValue(val value: String)

```

**Comment by schauder** [comment] 2022-08-29 14:08
Duplicate of https://github.com/spring-projects/spring-data-relational/issues/1093

**Closed as completed by schauder** 2022-08-29 14:08 UTC
Labels: status: duplicate, status: waiting-for-triage
