### ISSUE TITLE
IN CLAUSE and binding throws java.lang.IllegalArgumentException: Cannot encode null parameter of type java.util.List

### ISSUE THREAD

**Issue by mesutpiskin** [spring-projects/spring-data-r2dbc#732] opened 2022-02-23 13:10 UTC
I'm tring to bind a parameter with an IN clause for PostgreSQL

Spring: 2.3.1

```
  @Query("SELECT cp FROM MyTable cp WHERE  cp.Value in (:valueList)")
 Flux<MyData> getMyValues(Set<String> valueList);
```

I'm receiving the following exception

```
 {IllegalArgumentException@17194} Method threw 'java.lang.IllegalArgumentException' exception.
 backtrace = {Object[5]@17196} 
 detailMessage = "Cannot encode null parameter of type java.util.List"
 cause = {IllegalArgumentException@17194} "java.lang.IllegalArgumentException: Cannot encode null parameter of type java.util.List"
 stackTrace = {StackTraceElement[1]@17198} 
 depth = 97
 suppressedExceptions = {ArrayList@17199}  size = 2
```

**Comment by mp911de** [comment] 2022-02-23 13:15
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by spring-projects-issues** [comment] 2022-03-07 09:41
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-03-14 09:41
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-03-14 09:41 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
