### ISSUE TITLE
Add support for Json type 

### ISSUE THREAD

**Issue by darrenbkl** [spring-projects/spring-data-r2dbc#318] opened 2020-03-14 14:09 UTC
Since the postgresql driver has support for `io.r2dbc.postgresql.codec.Json`, documented here
https://github.com/r2dbc/r2dbc-postgresql#jsonjsonb-support, it would be great for Spring Data to also support it as entity field.

Currently if you have Json as a field type in your entity, you will get `org.springframework.dao.InvalidDataAccessApiUsageException: Nested entities are not supported`

A workaround is to register a custom converter with R2dbcCustomConversions
```
@WritingConverter
public class JsonConverter implements Converter<Json, Json> {
    @Override
    public Json convert(Json source) {
            return source;
    }
}
```

**Comment by darrenbkl** [comment] 2020-03-14 14:13
I would love to take this up, if you could point me to the right direction, thanks

**Comment by mp911de** [comment] 2020-03-16 08:18
Sure. Spring Data R2DBC considers `io.r2dbc.postgresql.codec.Json` as an entity type because it is not marked as a simple type. It should be sufficient to add `Json` to the simple type constant in `org.springframework.data.r2dbc.dialect.PostgresDialect` and come up with an integration test in `PostgresDatabaseClientIntegrationTests`.

Let me know if you require additional guidance.

**Comment by darrenbkl** [comment] 2020-03-27 16:30
@mp911de I followed your suggestion, and wrote a simple integration test that save a simple entity with a Json field into the db. 
```
@Table("json_type")
@Data
static class JsonType {
    @Id int id;
    Json j;
}
```

The error is gone, the record is created, but Json field is null. I traced that the json field somehow ends up as `org.springframework.data.r2dbc.dialect.Bindings.NullBinding`, but the id field ends up as `ValueBinding`, let me know if I missed something.

**Comment by mp911de** [comment] 2020-03-27 17:37
Thanks a lot. I’ll have a look in the next days.

**Comment by mp911de** [comment] 2020-03-31 10:26
The `null` issue is rooted in Spring Data Relational as it tries aggressively to convert values into entities. I filed https://jira.spring.io/browse/DATAJDBC-516 to fix the issue and I'll add JSON support here.

**Closed** 2020-03-31 10:38 UTC
Labels: type: enhancement

**Comment by limpygnome** [comment] 2021-05-26 14:36
Just to confirm, is this still expected to give null with the latest Spring Data? It looks like DATAJDBC-516 has since been closed.

I've got the following, dodgy, workaround:

````
    @Bean
    public R2dbcCustomConversions r2dbcCustomConversions() {

        try {

            List<Converter<?, ?>> converters = Arrays.asList(writeConverter, readConverter);

            Class clazz = Class.forName("io.r2dbc.postgresql.codec.Json$JsonByteArrayInput");
            Set<Class<?>> customTypes = new HashSet<>();
            customTypes.add(clazz);
            SimpleTypeHolder simpleTypeHolder = new SimpleTypeHolder(customTypes, true);

            CustomConversions.StoreConversions storeConversions = CustomConversions.StoreConversions.of(simpleTypeHolder, converters);

            R2dbcCustomConversions conversions = new R2dbcCustomConversions(storeConversions, converters);
            return conversions;

        } catch (ClassNotFoundException e) {
            throw new IllegalStateException("Unable to add Json sub-class as simple type");
        }
    }
````

The converters are used to convert between a custom class and `Json` in the r2dbc postgres driver, as @darrenbkl was doing.

Without the workaround, the problem seems to be when Spring data needs to decide whether to write data as a simple type, as you mentioned before:
````
org.springframework.data.r2dbc.convert.MappingR2dbcConverter#writeProperties

if (getConversions().isSimpleType(value.getClass())) {
    writeSimpleInternal(sink, value, isNew, property);
} else {
    writePropertyInternal(sink, value, isNew, property);
}
````

Adding just `Json` to the Postgres dialect, #318, doesn't seem to work? Should there be an extension to the area in #318 to also add `io.r2dbc.postgresql.codec.Json$JsonByteArrayInput`?

**Comment by mp911de** [comment] 2021-06-09 07:59
`JsonByteArrayInput` is a subtype of `Json` and the simple types check checks for assignability. We have [an integration test](https://github.com/spring-projects/spring-data-r2dbc/blob/2b4bc0d140da75e929a7b8a4e731e30ab11406ea/src/test/java/org/springframework/data/r2dbc/repository/PostgresR2dbcRepositoryIntegrationTests.java#L138-L155) that verifies the functionality. If the problem persists, please file a new ticket along with a reproducer.
