### ISSUE TITLE
DatabaseClient returns values in wrong order

### ISSUE THREAD

**Issue by Tienisto** [spring-projects/spring-data-r2dbc#478] opened 2020-10-12 11:14 UTC
Hello,

I tried to fetch data via `DatabaseClient`. However the values are in the wrong order.

Example:
```java
@Table("my_table")
public class MyEntity {

    @Id
    private Integer id;
    private int age;
    private String name;

    // getters and setters
}

@Repository
public class MyDatabaseClientRepo {

    private final DatabaseClient client;

    public MyDatabaseClientRepo(DatabaseClient client) {
        this.client = client;
    }

    public Flux<MyEntity> findAll() {
        return client.sql("SELECT * FROM my_table")
                .fetch()
                .all()
                .map(map -> {

                    /*
                     * table content
                     * id | age | name
                     * ---------------
                     *  1 |  24 |  max
                     */

                    System.out.println("id: " + map.get("id")); // returns 24
                    System.out.println("age: " + map.get("age")); // returns max
                    System.out.println("name: " + map.get("name")); // returns 1

                    int currId = (int) map.get("id");
                    int currAge = (int) map.get("age"); // error: cannot cast string to integer
                    String currName = (String) map.get("name");

                    MyEntity entity = new MyEntity();
                    entity.setId(currId);
                    entity.setAge(currAge);
                    entity.setName(currName);
                    return entity;
                });
    }
}
```

```sql
-- table
CREATE TABLE my_table (
    id SERIAL PRIMARY KEY,
    age INT NOT NULL,
    name TEXT NOT NULL
);
```

Stacktrace:
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
	at com.example.demo.MyDatabaseClientRepo.lambda$findAll$0(MyDatabaseClientRepo.java:34) ~[main/:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ Handler com.example.demo.MyController#get() [DispatcherHandler]
	|_ checkpoint ⇢ HTTP GET "/c" [ExceptionHandlingWebHandler]
Stack trace:
		at com.example.demo.MyDatabaseClientRepo.lambda$findAll$0(MyDatabaseClientRepo.java:34) ~[main/:na]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onNext(FluxUsingWhen.java:358) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmit(FluxFlatMap.java:542) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxFlatMap$FlatMapInner.onNext(FluxFlatMap.java:1006) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:118) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onNext(FluxTakeUntil.java:83) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:657) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:735) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:777) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:255) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxCreate$SerializedFluxSink.next(FluxCreate.java:154) ~[reactor-core-3.4.0-RC1.jar:na]
		at io.r2dbc.postgresql.client.ReactorNettyClient$Conversation.emit(ReactorNettyClient.java:725) ~[r2dbc-postgresql-0.8.5.RELEASE.jar:0.8.5.RELEASE]
		at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.emit(ReactorNettyClient.java:976) ~[r2dbc-postgresql-0.8.5.RELEASE.jar:0.8.5.RELEASE]
		at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:850) ~[r2dbc-postgresql-0.8.5.RELEASE.jar:0.8.5.RELEASE]
		at io.r2dbc.postgresql.client.ReactorNettyClient$BackendMessageSubscriber.onNext(ReactorNettyClient.java:757) ~[r2dbc-postgresql-0.8.5.RELEASE.jar:0.8.5.RELEASE]
		at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:118) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onNext(FluxPeekFuseable.java:854) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onNext(FluxMap.java:220) ~[reactor-core-3.4.0-RC1.jar:na]
		at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:256) ~[reactor-netty-core-1.0.0-RC1.jar:1.0.0-RC1]
		at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:362) ~[reactor-netty-core-1.0.0-RC1.jar:1.0.0-RC1]
		at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:374) ~[reactor-netty-core-1.0.0-RC1.jar:1.0.0-RC1]
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:94) ~[reactor-netty-core-1.0.0-RC1.jar:1.0.0-RC1]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[netty-codec-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[netty-codec-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425) ~[netty-codec-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.52.Final.jar:4.1.52.Final]
		at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

Version: 1.2.0-RC1
Database: PostgreSQL

**Comment by mp911de** [comment] 2020-10-12 14:28
Are you able to reproduce the issue by using the R2DBC SPI directly?

**Comment by Tienisto** [comment] 2020-10-12 15:31
Unfortunately, I have no idea how to use r2dbc spi directly

**Comment by Tienisto** [comment] 2020-10-13 20:55
Okay, I tested it on r2dbc spi. And it works, here is my code:
```java
public Flux<MyEntity> findAll() {
        ConnectionFactory connectionFactory = ConnectionFactories
                .get("r2dbc:postgresql://demo:123456@localhost:5432/demo");

        return Mono.from(connectionFactory.create())
                .flatMapMany(connection -> connection
                        .createStatement("SELECT * FROM my_table")
                        .execute())
                .flatMap(result -> result
                        .map((row, rowMetadata) -> {
                            System.out.println("id: " + row.get("id"));  // 1
                            System.out.println("age: " + row.get("age")); // 24
                            System.out.println("name: " + row.get("name")); // max
                            return new MyEntity();
                        }));
    }
```

**Comment by Tienisto** [comment] 2020-10-13 22:47
I think I got the issue.
It is actually in `org.springframework.r2dbc` and in `io.r2dbc.postgresql`.

The database client uses `org.springframework.r2dbc.core.ColumnMapRowMapper`.
Here is the method (I could not found the spring-r2dbc repo)
```java
        @Override
	public Map<String, Object> apply(Row row, RowMetadata rowMetadata) {
		Collection<String> columns = rowMetadata.getColumnNames();
		int columnCount = columns.size();
		Map<String, Object> mapOfColValues = createColumnMap(columnCount);
		int index = 0;
		for (String column : columns) {
			String key = getColumnKey(column);
			Object obj = getColumnValue(row, index++);
			mapOfColValues.put(key, obj);
		}
		return mapOfColValues;
	}
```

It assumes that column names from `rowMetadata.getColumnNames()` are in the same order as the sql result.
However the column names are in the alphabetical order.

Here is how in postgresql it is implemented:
```java
    private Collection<String> getColumnNames(List<PostgresqlColumnMetadata> columnMetadatas) {
        Set<String> columnNames = new TreeSet<>(IGNORE_CASE_COMPARATOR);

        for (PostgresqlColumnMetadata columnMetadata : columnMetadatas) {
            columnNames.add(columnMetadata.getName());
        }

        return columnNames;
    }
```

https://github.com/pgjdbc/r2dbc-postgresql/blob/cf86513f7c092a2114c4bc57a2d552d431c6f9a2/src/main/java/io/r2dbc/postgresql/PostgresqlRowMetadata.java#L128

**Comment by mp911de** [comment] 2020-10-14 09:23
Thanks a lot for investigating the issue. I can confirm that I observe the same behavior.

The R2DBC documentation says:

> The iteration order of the column names depends on the actual query result

`ColumnMapRowMapper` relies on the iteration order and looking into other drivers, this seems to be a driver issue.

I filed tickets in R2DBC SPI to extend the TCK and for the Postgres driver to fix the iteration order. Since the issue can be solved on the driver level, closing this ticket. 

Related, R2DBC is going to release Arabba-SR8 by next week that should ship with a driver fix.

**Closed by mp911de** 2020-10-14 09:23 UTC
Labels: type: regression
