### ISSUE TITLE
Enum aren't mapped to Strings when using QueryService

### ISSUE THREAD

**Issue by Blastman** [spring-projects/spring-data-r2dbc#533] opened 2021-02-04 15:59 UTC
I'm trying to convert string properties to use Enums on DTOs and my entities. I registered the custom mappers and it reads the rows just fine but when I use the Query API, it keeps the query parameter as an enum instead of using my custom mapper. Also, if I try to use the string DB value, my custom mapper is hit and gets converted to the Enum. I believe the issue is [here](https://github.com/spring-projects/spring-data-r2dbc/blob/master/src/main/java/org/springframework/data/r2dbc/query/QueryMapper.java#L755) in that it defaults the conversion to the property type and later on ends up using the Enum name vs the value I define in my Enum -> String converter.  Some related code to duplicate issue:

```java
public class User {
  @Column("id")
  private Integer UserId;

  @Column("UserStatus")
  private UserStatus userStatus;
   ...
}
```

```java
public enum UserStatus { 
  ACTIVE("A"),
  INACTIVE("I")

  private final String dbValue;

  UserStatus(String dbValue){
    this.dbValue = dbValue;
  }
```

```java
// Custom mappers and registering them left out for briefly
```

Query code:

```java
Query query = Criteria.where("UserStatus").is(UserStatus.ACTIVE);
r2dbcEntityTemplate.select(query, User.class) // Always returns 0 rows since no rows match "ACTIVE"/"INACTIVE"
```

**Comment by mp911de** [comment] 2021-02-08 15:21
Care to provide a reproducible sample? I'm missing right now how the SQL side (table definition) looks like.

**Comment by spring-projects-issues** [comment] 2021-02-15 15:22
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-02-22 15:22
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-02-22 15:22 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
