### ISSUE TITLE
UUID MappingException after upgrading spring-boot 2.5.0 to 2.5.2 

### ISSUE THREAD

**Issue by RobertHeim** [spring-projects/spring-data-r2dbc#613] opened 2021-06-29 10:33 UTC
Having an entity that uses `UUID` as `@Id`:
```
data class Avatar(
  // id is generated by postgres default value
  @Id
  val id: UUID? = null,
)
```
and this repository:
```
@Repository
interface AvatarRepository : CoroutineCrudRepository<Avatar, UUID> {
  suspend fun findIdByUserId(id: Long): UUID?
  // ..
}
```
I updated spring boot from 2.5.0 to 2.5.2 and now the `findIdByUserId` query throws:
```
org.springframework.data.mapping.MappingException: Couldn't find PersistentEntity for type class java.util.UUID!
	at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:79) ~[spring-data-commons-2.5.2.jar:2.5.2]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
// ...
Stack trace:
		at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:79) ~[spring-data-commons-2.5.2.jar:2.5.2]
		at org.springframework.data.relational.repository.query.DtoInstantiatingConverter.<init>(DtoInstantiatingConverter.java:61) ~[spring-data-relational-2.2.2.jar:2.2.2]
		at org.springframework.data.r2dbc.repository.query.R2dbcQueryExecution$ResultProcessingConverter.convert(R2dbcQueryExecution.java:112) ~[spring-data-r2dbc-1.3.2.jar:1.3.2]
		at org.springframework.data.r2dbc.repository.query.R2dbcQueryExecution$ResultProcessingExecution.execute(R2dbcQueryExecution.java:64) ~[spring-data-r2dbc-1.3.2.jar:1.3.2]
		at org.springframework.data.r2dbc.repository.query.AbstractR2dbcQuery.executeQuery(AbstractR2dbcQuery.java:125) ~[spring-data-r2dbc-1.3.2.jar:1.3.2]
		at org.springframework.data.r2dbc.repository.query.AbstractR2dbcQuery.lambda$execute$0(AbstractR2dbcQuery.java:91) ~[spring-data-r2dbc-1.3.2.jar:1.3.2]
```
The relevant dependencies:
```
plugins {
  id("org.springframework.boot") version "2.5.2"
  id("io.spring.dependency-management") version "1.0.11.RELEASE"
  kotlin("jvm") version "1.5.20"
  kotlin("plugin.spring") version "1.5.20"
  jacoco
}
// ...
dependencies {
  implementation("org.springframework.boot:spring-boot-starter-data-r2dbc")
  implementation("io.r2dbc:r2dbc-postgresql")
  runtimeOnly("org.postgresql:postgresql")
  // ...
}
```

PS: In 2.5.1 this seems to be no problem.

**Comment by mp911de** [comment] 2021-06-29 11:48
Thanks for report. This is a duplicate of #612 when a query method returns a simple type.

**Closed by mp911de** 2021-06-29 11:48 UTC
Labels: status: duplicate, status: waiting-for-triage
