### ISSUE TITLE
java.lang.IllegalStateException: Required property not found for class

### ISSUE THREAD

**Issue by etnoy** [spring-projects/spring-data-r2dbc#320] opened 2020-03-18 23:03 UTC
I am quite new to reactive programming, so apologies if I am reporting this to the wrong project or if I am missing something obvious.

Currently I am playing around with a small project of mine. Previously I used spring data jdbc + mysql, but wanted to try reactive programming. I am using embedded entities, which in r2dbc are not supported. Instead, I intend to assemble my entity hierarchy in the service layer.

In my migration from spring data jdbc to r2dbc I mark my embedded entities as `@Transient` since they are not to be stored in the database. However, I get the following error which I am unable to work around:

`java.lang.IllegalStateException: Required property auth not found for class mwe.User!
	at org.springframework.data.mapping.PersistentEntity.getRequiredPersistentProperty(PersistentEntity.java:160)`

(I've removed most of the above stack trace)

Here, the relevant code of the entity is as follows:

```
public class User {

  @Id
  private final int id;

  @Transient
  private final Auth auth;

}
```

where `auth` is another entity that holds the user's auth data.

Somehow, it appears that `@Transient` isn't doing what I want. I want r2dbc to just ignore that field and create a null auth object when loading from the repository.

For a full minimal example of a project that throws this exception, please see https://github.com/etnoy/r2dbc-required-property-not-found

Thanks.

**Comment by mp911de** [comment] 2020-03-19 10:04
The issue is that the `User` class declares a constructor of `(int id, Auth auth)` while the `auth` property is marked as transient. Spring Data identifies the sole constructor as persistence constructor to create persistent entities when reading from the database. Since `auth` is excluded, Spring Data has no chance to materialize a value for that argument.

**Closed by mp911de** 2020-03-19 10:04 UTC
Labels: status: invalid

**Comment by etnoy** [comment] 2020-03-19 10:53
That explains it! The spring data r2dbc documentation is a bit terse and I am not very seasoned in Java which confused me. Using lombok makes it a bit harder, too, since it isn't always obvious what is generated and what is not.

I solved the problem by manually adding a constructor for all arguments except the transient one. Then, I marked this constructor with `@PersistenceConstructor` and added lombok's `@AllArgsConstructor` to the class. This allowed me to continue using lombok's Builder annotation.

Hope this helps future googlers, too.

**Comment by mp911de** [comment] 2020-03-19 13:15
Great to hear you were able to sort out the issue. It makes sense to mention the effect of `@Transient` on persistence constructors.

**Comment by JoseLion** [comment] 2021-05-06 06:44
@mp911de I know this is already closed, but even though the `@PersistenceConstructor` approach works, it could also make things hard to maintain. Entities could potentially have a lot of fields because they map to tables in the database, right?

So let's say we have a table with 20 columns, plus 4 auditable columns, plus the PK column. We will end up with a 25 fields entity, and if we need to add a transient field, we'll have to maintain 2 really big constructors, which will be very confusing to handle, in my opinion. 😅 

Since we already have fields annotated with `@Transient`, is there any way to identify the transient fields in the constructor and materialize them with `null`, or even better, a default value? I'm not completely sure of the implications of this, but transient values should be handled somehow at some point by the application itself, so it doesn't seem to be harmful at first glance. 😁 

I think this would be really helpful, especially when working with big entities and immutable classes. And as always, I'm happy to contribute if possible.

Cheers!

**PS:** I can open a separate issue if necessary, given this one's been closed for something more than a year. 😅

**Comment by mp911de** [comment] 2021-05-06 06:48
Why don't you remove the transient properties from the `@PersistenceConstructor`? That seems to be the easiest way out. Other than that, you can annotate constructor parameters with `@Value("null")` to let the converter materialize a `null` value.

**Comment by JoseLion** [comment] 2021-05-06 07:40
Right, so to keep the class immutable, I'm using `withers`, so I still need the constructor with the transient properties to populate them later. 😅 

Honestly, I'm using Lombok to achieve immutability and reduce boilerplate, so my entities look something like this:
```java
@With
@Table
@Value
@Builder(access = AccessLevel.PRIVATE)
public class Account implements BaseModel<JobPosition> {

  private @Default Long id = null;
  
  private @Default String username = "";

  private @Default String password = "";

  /* more fields... */
  
  @Transient
  private @Nullable String someProp;

  public static Account init() {
    return Account.builder().build();
  }
}
```

However, adding `@Value("null")` to the transient property did the trick! For Lombok to pass the annotation to the constructor parameter, I just had to add the following to my `lombok.config` file:
```
lombok.copyableAnnotations += org.springframework.beans.factory.annotation.Value
```

Honestly, I was not sure how `@Value` worked, but given it allows us to control how the converter materialize transient fields, I think that's more than enough for what I was asking before 😄 

Thank you so much for the help on this and the quick response! 🎉
