### ISSUE TITLE
How to achieve One to Many relationship with Spring data JDBC with R2DBC(Mysql)

### ISSUE THREAD

**Issue by Sugumar007** [spring-projects/spring-data-r2dbc#445] opened 2020-09-06 14:25 UTC
Hi Team, I am facing one issue I am not able to find correct way to achieve Association in Spring data JDBC with R2DBC(Mysql)

For Example,

**Employee** is one entity and **Address** sub entity of **Employee**. One employee can have many addresses so How I achieve this functionality using R2dbc(Mysql) with Spring Data JDBC.
If I delete a employee, the foreign relationship address should also get deleted.
I am new to spring world, Please help guys

**Comment by mp911de** [comment] 2020-09-07 11:56
Mapped relationships aren't supported yet. Duplicate of #356.

**Closed by mp911de** 2020-09-07 11:56 UTC
