### ISSUE TITLE
MSSQL statement execution errors have no effect while using ReactiveCrudRepository

### ISSUE THREAD

**Issue by r2dbc-byte** [spring-projects/spring-data-r2dbc#555] opened 2021-03-13 12:19 UTC
```
SELECT @@version;

Microsoft SQL Server 2017 (RTM-CU22-GDR) (KB4583457) - 14.0.3370.1 (X64) 
	Nov  6 2020 18:19:52 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)
```

Sample application to reproduce the issue: https://github.com/r2dbc-byte/spring-data-r2dbc-test

On startup, the application creates a table with the following structure:

```
CREATE TABLE person (
  id INT IDENTITY(1,1) PRIMARY KEY, 
  name VARCHAR(100) NOT NULL UNIQUE
);
```

Field `name` is unique. 

The application exposes the following endpoint to create records in the `person` table:

```
GET http://localhost:8080/test?name=John
```

When we insert a record for the first time, everything runs as expected: the person instance is returned with the auto generated id and the record is stored in the database.

If we try to insert a record which violates the unique constraint - using a name that already exists - the execution proceeds up until the end like if no error happened, but this time returning a person which id is null (no record is stored in the database and the next auto generated identifier value is consumed, which seems to confirm the roundtrip followed by the error).

The TRACE logs, and also following the execution inside `TransactionSynchronizationManager`, seem to indicate that the transaction is committed like if there was no error.

If we try the same using a `DatabaseClient` instance directly, everything works as expected and errors are correctly propagated upstream.

I have redacted the property values from the sample database configuration class, but kept the structure unchanged: https://github.com/r2dbc-byte/spring-data-r2dbc-test/blob/master/src/main/java/com/example/reactiverestservice/ApplicationConfiguration.java

**Comment by r2dbc-byte** [comment] 2021-03-13 17:18
Additional information: testing the sample application against H2 yields the correct behaviour (unique constraint violation error is propagated upstream)

**Comment by mp911de** [comment] 2021-03-15 15:44
This is a duplicate of #552.

**Closed by mp911de** 2021-03-15 15:44 UTC
Labels: status: duplicate

**Comment by r2dbc-byte** [comment] 2021-03-15 17:14
Apologies for the duplicate!
