### ISSUE TITLE
IN CLAUSE and binding throws java.lang.IllegalArgumentException for derived queries

### ISSUE THREAD

**Issue by DarkSeraphim** [spring-projects/spring-data-r2dbc#361] opened 2020-05-06 16:36 UTC
Similar to #178 , but with derived queries instead of using the @Query annotation. A sample snippet would be something like
```kotlin
data class Item (
    @Id
    val id: Long? = null,
    val name: String
)

@Repository
interface ItemRepository : ReactiveCrudRepository<Item, Long> {
  fun findAllByNameIn(names: Collection<String>): Flux<Item>
}
```

This will compile, but when trying to run the findAllByNameIn method, you encounter a familiar error (as it is the same error as with #178, but with a different driver implementation):
```
java.lang.IllegalArgumentException: Cannot encode parameter of type java.util.ArrayList
	at io.r2dbc.postgresql.codec.DefaultCodecs.encode(DefaultCodecs.java:143) ~[r2dbc-postgresql-0.8.2.RELEASE.jar:0.8.2.RELEASE]
	at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement.bind(ExtendedQueryPostgresqlStatement.java:84) ~[r2dbc-postgresql-0.8.2.RELEASE.jar:0.8.2.RELEASE]
	at io.r2dbc.postgresql.ExtendedQueryPostgresqlStatement.bind(ExtendedQueryPostgresqlStatement.java:45) ~[r2dbc-postgresql-0.8.2.RELEASE.jar:0.8.2.RELEASE]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.lambda$bindByIndex$11(DefaultDatabaseClient.java:311) ~[spring-data-r2dbc-1.1.0.RC1.jar:1.1.0.RC1]
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:na]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.bindByIndex(DefaultDatabaseClient.java:307) ~[spring-data-r2dbc-1.1.0.RC1.jar:1.1.0.RC1]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.access$700(DefaultDatabaseClient.java:74) ~[spring-data-r2dbc-1.1.0.RC1.jar:1.1.0.RC1]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient$ExecuteSpecSupport.lambda$exchange$1(DefaultDatabaseClient.java:394) ~[spring-data-r2dbc-1.1.0.RC1.jar:1.1.0.RC1]
	at org.springframework.data.r2dbc.core.DefaultDatabaseClient.lambda$null$17(DefaultDatabaseClient.java:1520) ~[spring-data-r2dbc-1.1.0.RC1.jar:1.1.0.RC1]
```
After a bit of digging, it seems to boil down to the fact that the lists aren't expanded, but just passed to the driver as-is (which then fails to encode it). When using named parameters (with a @Query annotation), it seems to work fine, but that means I'm still writing my own queries.

To me, the expected behaviour would be that it expands parameters when their type is a subtype of Iterable / Collection, as it currently does for named parameters in @Query.

Spring Boot version: 2.3.0.M4
Java version: OpenJDK 13.0.2

**Comment by mp911de** [comment] 2020-05-11 13:14
Thanks for report. The issue is caused by a component in Spring Data Relational and will be fixed with DATAJDBC-539.

**Closed** 2020-05-11 13:31 UTC
Labels: for: external-project, type: bug
