### ISSUE TITLE
we need primary key generator strategy

### ISSUE THREAD

**Issue by NotFound403** [spring-projects/spring-data-r2dbc#417] opened 2020-07-27 03:24 UTC
when i  insert a new record without id  and  my database id strategy is snowflake algorithm, i cant  insert it.  when i do it with snowflake id  again   , but the operation is updating which i dont expect .    so  i  need  a  cut point  to define my custom.
```java
    @Test
    void springDataR2dbc(){
        ClientUser clientUser = new ClientUser();


        clientUser.setGender(2);
        clientUser.setNickName("r2dbc");
        clientUser.setPhoneNumber("9527");
        //the system id strategy is snowflake  ,  the next opteration    will  update  but i need to insert
        clientUser.setUserId("snowflake");

        Mono<ClientUser> save = clientUserRepository.save(clientUser);
                 save.as(StepVerifier::create)
                         .expectNextCount(1)
                         .verifyComplete();

    }
```

the source code in spring data r2dbc
```java
	@Override
	@Transactional
	public <S extends T> Mono<S> save(S objectToSave) {

		Assert.notNull(objectToSave, "Object to save must not be null!");

		if (this.entity.isNew(objectToSave)) {
                      //  maybe some strategy here is better
			return this.entityOperations.insert(objectToSave);
		}

		return this.entityOperations.update(objectToSave);
	}
```

**Comment by mp911de** [comment] 2020-07-27 09:05
Here's the link to the reference documentation that describes Spring Data's [Entity State Detection Strategies](https://docs.spring.io/spring-data/r2dbc/docs/current/reference/html/#r2dbc.entity-persistence.state-detection-strategies). 

Duplicate of #404.

**Closed by mp911de** 2020-07-27 09:05 UTC
Labels: status: duplicate
