### ISSUE TITLE
Update support using untyped operations: Is not possible set multiple columns to update

### ISSUE THREAD

**Issue by eriknyk** [spring-projects/spring-data-r2dbc#195] opened 2019-09-25 20:06 UTC
From docs:

*Update also support untyped operations:*

![image](https://user-images.githubusercontent.com/205721/65635067-3d25dc00-dfa5-11e9-8fd9-cc804d1dd559.png)

How multiple column/value can be added to Update.update(..) object,
seems can only accept one single column to update not multiple, and that can be see in the code: https://github.com/spring-projects/spring-data-r2dbc/blob/master/src/main/java/org/springframework/data/r2dbc/query/Update.java#L60

```
public class Update {

	private static final Update EMPTY = new Update(Collections.emptyMap());

	private final Map<String, Object> columnsToUpdate;

	private Update(Map<String, Object> columnsToUpdate) {
		this.columnsToUpdate = columnsToUpdate;
	}

	/**
	 * Static factory method to create an {@link Update} using the provided column.
	 *
	 * @param column must not be {@literal null}.
	 * @param value can be {@literal null}.
	 * @return
	 */
	public static Update update(String column, @Nullable Object value) {
		return EMPTY.set(column, value);
	}

	/**
	 * Update a column by assigning a value.
	 *
	 * @param column must not be {@literal null}.
	 * @param value can be {@literal null}.
	 * @return
	 */
	public Update set(String column, @Nullable Object value) {
		return addMultiFieldOperation(column, value);
	}

	/**
	 * Returns all assignments.
	 *
	 * @return
	 */
	public Map<String, Object> getAssignments() {
		return Collections.unmodifiableMap(this.columnsToUpdate);
	}

	private Update addMultiFieldOperation(String key, Object value) {

		Assert.hasText(key, "Column for update must not be null or blank");

		Map<String, Object> updates = new LinkedHashMap<>(this.columnsToUpdate);
		updates.put(key, value);

		return new Update(updates);
	}
}
```
On creation time it initializes its internal Map object with an EMPTY map
and it does not allow pass a custom map with defined columns to update.
And the Update.set() method is always overriding previous column/value set, what is causing that it accepts *only* one single column for the update.

So, according the docs, and following the code, it should accept multiple columns with something like:

```
        var x = Update.update("c1", "a")
                .set("c2", "b")
                .set("c3", "c");
```

but it doesn't work actually, and it is happening because on *addMultiFieldOperation()* method a new Map `Map<String, Object> updates = new LinkedHashMap<>(this.columnsToUpdate);` is always created from `this.columnsToUpdate` that always is EMPTY

Best Regards.

**Comment by mp911de** [comment] 2019-09-26 06:51
Have you tried `Update.update("column1", "value1").set("column2", "value2")`?

**Comment by mp911de** [comment] 2019-10-29 14:36
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by mp911de** [comment] 2019-12-06 08:41
I wasn't able to reproduce the mentioned issue. `addMultiFieldOperation(…)` creates a new `Map` that is initialized from the current `map` and gets the current assignment added. So it's incrementally building a `Update` that contains all assignments:

The following test is passing:

```java
Update update = Update.update("c1", "a").set("c2", "b").set("c3", "c");

assertThat(update.getAssignments()).hasSize(3);
```

I added a test to verify multi-assignments are working.

**Closed by mp911de** 2019-12-06 08:41 UTC
Labels: status: waiting-for-triage
