### ISSUE TITLE
Repositories not detected by @EnableR2dbcRepositories annotation

### ISSUE THREAD

**Issue by sons-of-titus** [spring-projects/spring-data-r2dbc#862] opened 2024-07-25 06:29 UTC
## Description
The `@EnableR2dbcRepositories` annotation is not detecting and initializing my R2DBC repositories as expected. This is preventing my application from properly interacting with the database using Spring Data R2DBC.

## Current Behavior
When starting the application, no beans are created for my repository interfaces. This results in `NoSuchBeanDefinitionException` when trying to autowire these repositories.

## Expected Behavior
The `@EnableR2dbcRepositories` annotation should detect all interfaces extending `CoroutineCrudRepository` (or other Spring Data R2DBC repository interfaces) within the specified base packages, and create the necessary beans for these repositories.

## Steps to Reproduce
1. Annotated main application class or configuration class with `@EnableR2dbcRepositories`.
2. Created repository interfaces extending `CoroutineCrudRepository` in a submodule.
3. Attempted to autowire these repositories in service classes.
4. Started the application.

## Code Snippets

Main Application Class:
```kotlin
@SpringBootApplication(scanBasePackages = ["mr.hawel"])
@EnableR2dbcRepositories(basePackages = ["mr.hawel.user.persistence"])
class MyApplication

fun main(args: Array<String>) {
    runApplication<MyApplication>(*args)
}
```
UserR2dbcRepository Interface:
```kotlin
@Repository
interface UserR2dbcRepository : CoroutineCrudRepository<UserEntity, UUID> {
    suspend fun findByPhoneNumber(phoneNumber: String): UserEntity?
}
```
### Versions:
- spring-boot-starter-data-r2dbc : 3.3.2

**Comment by mp911de** [comment] 2024-07-26 07:29
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal yet complete sample](https://stackoverflow.com/help/mcve) that reproduces the problem.
You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by spring-projects-issues** [comment] 2024-08-02 07:32
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2024-08-09 07:32
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed as not planned by spring-projects-issues** 2024-08-09 07:32 UTC
