### ISSUE TITLE
No parameter specified for [namedParameter] in query when using multiple repeated array placeholders

### ISSUE THREAD

**Issue by rjbgaspar** [spring-projects/spring-data-r2dbc#739] opened 2022-03-17 18:17 UTC
Hi,
I’ve try to use the the Query annotation has follow 

Repository interface

```java
@Repository
public interface ACL247WIPRepository extends ReactiveCrudRepository<ACL247WIP, String>, ACL247WIPRepositoryInternal {
    // (...)
    @Query(
        "SELECT " +
        "   * " +
        "FROM acl_247_wips " +
        "INNER JOIN ( " +
        "   SELECT " +
        "        manufacturing_plan " +
        "       ,work_order " +
        "       ,max(created_at) AS latest_date\n" +
        "   FROM acl_247_wips " +
        "   WHERE " +
        "           (COALESCE(:manufacturingPlan,'') = '' OR manufacturing_plan IN (:manufacturingPlan)) " +
        "       AND (COALESCE(:workOrder,'') = '' OR work_order IN (:workOrder)) " +
        "   GROUP BY " +
        "        manufacturing_plan " +
        "       ,work_order " +
        ") SubMax ON ( " +
        "       SubMax.manufacturing_plan = acl_247_wips.manufacturing_plan " +
        "   AND SubMax.work_order = acl_247_wips.work_order " +
        "   AND SubMax.latest_date = acl_247_wips.created_at " +
        ")"
    )
    Flux<ACL247WIP> findAllByLastCreatedAtGroupByWorkOrder(String[] manufacturingPlan, String[] workOrder);
    // (...)
}
```
And when the method is executed I get `No parameter specified for [workOrder] in query`, this is the stack trace

```
org.springframework.dao.InvalidDataAccessApiUsageException: No parameter specified for [workOrder] in query [SELECT    * FROM acl_247_wips INNER JOIN (    SELECT         manufacturing_plan        ,work_order        ,max(created_at) AS latest_date
   FROM acl_247_wips    WHERE            (COALESCE(:manufacturingPlan,'') = '' OR manufacturing_plan IN (:manufacturingPlan))        AND (COALESCE(:workOrder,'') = '' OR work_order IN (:workOrder))   GROUP BY         manufacturing_plan        ,work_order ) SubMax ON (        SubMax.manufacturing_plan = acl_247_wips.manufacturing_plan    AND SubMax.work_order = acl_247_wips.work_order    AND SubMax.latest_date = acl_247_wips.created_at )]
	at org.springframework.data.r2dbc.core.DefaultReactiveDataAccessStrategy.processNamedParameters(DefaultReactiveDataAccessStrategy.java:316)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoMapFuseable] :
	reactor.core.publisher.Mono.map(Mono.java:3411)
	org.springframework.data.r2dbc.repository.query.StringBasedR2dbcQuery.createQuery(StringBasedR2dbcQuery.java:156)
Error has been observed at the following site(s):
	*_______________Mono.map ⇢ at org.springframework.data.r2dbc.repository.query.StringBasedR2dbcQuery.createQuery(StringBasedR2dbcQuery.java:156)
	|_      Mono.flatMapMany ⇢ at org.springframework.data.r2dbc.repository.query.AbstractR2dbcQuery.execute(AbstractR2dbcQuery.java:88)
	*_________Flux.usingWhen ⇢ at org.springframework.data.repository.core.support.RepositoryMethodInvoker$ReactiveInvocationListenerDecorator.decorate(RepositoryMethodInvoker.java:242)
	*_________Flux.usingWhen ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.lambda$null$8(TransactionAspectSupport.java:944)
	|_    Flux.onErrorResume ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.lambda$null$8(TransactionAspectSupport.java:957)
	*______________Mono.then ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.lambda$null$7(TransactionAspectSupport.java:958)
	*_______Mono.flatMapMany ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.lambda$invokeWithinTransaction$9(TransactionAspectSupport.java:940)
	*_______Mono.flatMapMany ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.invokeWithinTransaction(TransactionAspectSupport.java:939)
	|_     Flux.contextWrite ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.invokeWithinTransaction(TransactionAspectSupport.java:964)
	|_     Flux.contextWrite ⇢ at org.springframework.transaction.interceptor.TransactionAspectSupport$ReactiveTransactionSupport.invokeWithinTransaction(TransactionAspectSupport.java:965)
	|_              Flux.map ⇢ at org.springframework.http.codec.json.AbstractJackson2Encoder.encode(AbstractJackson2Encoder.java:168)
	|_ Flux.doAfterTerminate ⇢ at org.springframework.http.codec.json.AbstractJackson2Encoder.encode(AbstractJackson2Encoder.java:170)
	|_              Flux.map ⇢ at org.springframework.http.codec.EncoderHttpMessageWriter.write(EncoderHttpMessageWriter.java:144)
	|_        Mono.doOnError ⇢ at org.springframework.http.server.reactive.AbstractServerHttpResponse.writeAndFlushWith(AbstractServerHttpResponse.java:248)
	|_            checkpoint ⇢ Handler com.gv.panther.web.rest.ACL247WIPExtendedResource#findAllByLastCreatedAtGroupByWorkOrder(MultiValueMap) [DispatcherHandler]
Original Stack Trace:
		at org.springframework.data.r2dbc.core.DefaultReactiveDataAccessStrategy.processNamedParameters(DefaultReactiveDataAccessStrategy.java:316)
		at org.springframework.data.r2dbc.core.DefaultReactiveDataAccessStrategy.processNamedParameters(DefaultReactiveDataAccessStrategy.java:60)
		at org.springframework.data.r2dbc.repository.query.StringBasedR2dbcQuery$ExpandedQuery.<init>(StringBasedR2dbcQuery.java:201)
		at org.springframework.data.r2dbc.repository.query.StringBasedR2dbcQuery.lambda$createQuery$0(StringBasedR2dbcQuery.java:156)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
		at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:101)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
		at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:368)
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onComplete(FluxConcatMap.java:276)
		at reactor.core.publisher.Operators.complete(Operators.java:137)
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:148)
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
		at reactor.core.publisher.Flux.subscribe(Flux.java:8469)
		at reactor.core.publisher.FluxUsingWhen.subscribe(FluxUsingWhen.java:94)
		(...)
```
If i change the method signature as follow, e.g.:

```java
@Repository
public interface ACL247WIPRepository extends ReactiveCrudRepository<ACL247WIP, String>, ACL247WIPRepositoryInternal {
    // (...)
    @Query(
        "SELECT " +
        "   * " +
        "FROM acl_247_wips " +
        "INNER JOIN ( " +
        "   SELECT " +
        "        manufacturing_plan " +
        "       ,work_order " +
        "       ,max(created_at) AS latest_date\n" +
        "   FROM acl_247_wips " +
        "   WHERE " +
        "           (COALESCE(:manufacturingPlan1,'') = '' OR manufacturing_plan IN (:manufacturingPlan2)) " +
        "       AND (COALESCE(:workOrder1,'') = '' OR work_order IN (:workOrder2)) " +
        "   GROUP BY " +
        "        manufacturing_plan " +
        "       ,work_order " +
        ") SubMax ON ( " +
        "       SubMax.manufacturing_plan = acl_247_wips.manufacturing_plan " +
        "   AND SubMax.work_order = acl_247_wips.work_order " +
        "   AND SubMax.latest_date = acl_247_wips.created_at " +
        ")"
    )
    Flux<ACL247WIP> findAllByLastCreatedAtGroupByWorkOrder(
        String[] manufacturingPlan1, String[] manufacturingPlan2, String[] workOrder1,  String[] workOrder2);
    // (...)
}
```
it will work...

<details>
  <summary>ACL247WIP Entity class</summary>

```java
package com.gv.panther.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.Instant;
import javax.validation.constraints.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

/**
 * A ACL247WIP.
 */
@Table("acl_247_wips")
public class ACL247WIP implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column("id")
    private String id;

    @Column("manufacturing_plan")
    private String manufacturingPlan;

    @NotNull(message = "must not be null")
    @Column("work_order")
    private String workOrder;

    @NotNull(message = "must not be null")
    @Size(max = 20)
    @Column("item_code")
    private String itemCode;

    @Column("item_description")
    private String itemDescription;

    @Size(max = 15)
    @Column("item_lot")
    private String itemLot;

    @Column("length")
    private BigDecimal length;

    @Column("width")
    private BigDecimal width;

    @Column("thickness")
    private BigDecimal thickness;

    @NotNull(message = "must not be null")
    @Column("work_area_one")
    private String workAreaOne;

    @Column("script_one")
    private String scriptOne;

    @Column("program_one")
    private String programOne;

    @NotNull(message = "must not be null")
    @Column("work_area_two")
    private String workAreaTwo;

    @Column("script_two")
    private String scriptTwo;

    @Column("program_two")
    private String programTwo;

    @Column("created_at")
    private Instant createdAt;

    @Column("updated_at")
    private Instant updatedAt;



    public String getId() {
        return this.id;
    }

    public ACL247WIP id(String id) {
        this.setId(id);
        return this;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getManufacturingPlan() {
        return this.manufacturingPlan;
    }

    public ACL247WIP manufacturingPlan(String manufacturingPlan) {
        this.setManufacturingPlan(manufacturingPlan);
        return this;
    }

    public void setManufacturingPlan(String manufacturingPlan) {
        this.manufacturingPlan = manufacturingPlan;
    }

    public String getWorkOrder() {
        return this.workOrder;
    }

    public ACL247WIP workOrder(String workOrder) {
        this.setWorkOrder(workOrder);
        return this;
    }

    public void setWorkOrder(String workOrder) {
        this.workOrder = workOrder;
    }

    public String getItemCode() {
        return this.itemCode;
    }

    public ACL247WIP itemCode(String itemCode) {
        this.setItemCode(itemCode);
        return this;
    }

    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    public String getItemDescription() {
        return this.itemDescription;
    }

    public ACL247WIP itemDescription(String itemDescription) {
        this.setItemDescription(itemDescription);
        return this;
    }

    public void setItemDescription(String itemDescription) {
        this.itemDescription = itemDescription;
    }

    public String getItemLot() {
        return this.itemLot;
    }

    public ACL247WIP itemLot(String itemLot) {
        this.setItemLot(itemLot);
        return this;
    }

    public void setItemLot(String itemLot) {
        this.itemLot = itemLot;
    }

    public BigDecimal getLength() {
        return this.length;
    }

    public ACL247WIP length(BigDecimal length) {
        this.setLength(length);
        return this;
    }

    public void setLength(BigDecimal length) {
        this.length = length != null ? length.stripTrailingZeros() : null;
    }

    public BigDecimal getWidth() {
        return this.width;
    }

    public ACL247WIP width(BigDecimal width) {
        this.setWidth(width);
        return this;
    }

    public void setWidth(BigDecimal width) {
        this.width = width != null ? width.stripTrailingZeros() : null;
    }

    public BigDecimal getThickness() {
        return this.thickness;
    }

    public ACL247WIP thickness(BigDecimal thickness) {
        this.setThickness(thickness);
        return this;
    }

    public void setThickness(BigDecimal thickness) {
        this.thickness = thickness != null ? thickness.stripTrailingZeros() : null;
    }

    public String getWorkAreaOne() {
        return this.workAreaOne;
    }

    public ACL247WIP workAreaOne(String workAreaOne) {
        this.setWorkAreaOne(workAreaOne);
        return this;
    }

    public void setWorkAreaOne(String workAreaOne) {
        this.workAreaOne = workAreaOne;
    }

    public String getScriptOne() {
        return this.scriptOne;
    }

    public ACL247WIP scriptOne(String scriptOne) {
        this.setScriptOne(scriptOne);
        return this;
    }

    public void setScriptOne(String scriptOne) {
        this.scriptOne = scriptOne;
    }

    public String getProgramOne() {
        return this.programOne;
    }

    public ACL247WIP programOne(String programOne) {
        this.setProgramOne(programOne);
        return this;
    }

    public void setProgramOne(String programOne) {
        this.programOne = programOne;
    }

    public String getWorkAreaTwo() {
        return this.workAreaTwo;
    }

    public ACL247WIP workAreaTwo(String workAreaTwo) {
        this.setWorkAreaTwo(workAreaTwo);
        return this;
    }

    public void setWorkAreaTwo(String workAreaTwo) {
        this.workAreaTwo = workAreaTwo;
    }

    public String getScriptTwo() {
        return this.scriptTwo;
    }

    public ACL247WIP scriptTwo(String scriptTwo) {
        this.setScriptTwo(scriptTwo);
        return this;
    }

    public void setScriptTwo(String scriptTwo) {
        this.scriptTwo = scriptTwo;
    }

    public String getProgramTwo() {
        return this.programTwo;
    }

    public ACL247WIP programTwo(String programTwo) {
        this.setProgramTwo(programTwo);
        return this;
    }

    public void setProgramTwo(String programTwo) {
        this.programTwo = programTwo;
    }

    public Instant getCreatedAt() {
        return this.createdAt;
    }

    public ACL247WIP createdAt(Instant createdAt) {
        this.setCreatedAt(createdAt);
        return this;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return this.updatedAt;
    }

    public ACL247WIP updatedAt(Instant updatedAt) {
        this.setUpdatedAt(updatedAt);
        return this;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof ACL247WIP)) {
            return false;
        }
        return id != null && id.equals(((ACL247WIP) o).id);
    }

    @Override
    public int hashCode() {
        // see https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/
        return getClass().hashCode();
    }

    // prettier-ignore
    @Override
    public String toString() {
        return "ACL247WIP{" +
            "id=" + getId() +
            ", manufacturingPlan='" + getManufacturingPlan() + "'" +
            ", workOrder='" + getWorkOrder() + "'" +
            ", itemCode='" + getItemCode() + "'" +
            ", itemDescription='" + getItemDescription() + "'" +
            ", itemLot='" + getItemLot() + "'" +
            ", length=" + getLength() +
            ", width=" + getWidth() +
            ", thickness=" + getThickness() +
            ", workAreaOne='" + getWorkAreaOne() + "'" +
            ", scriptOne='" + getScriptOne() + "'" +
            ", programOne='" + getProgramOne() + "'" +
            ", workAreaTwo='" + getWorkAreaTwo() + "'" +
            ", scriptTwo='" + getScriptTwo() + "'" +
            ", programTwo='" + getProgramTwo() + "'" +
            ", createdAt='" + getCreatedAt() + "'" +
            ", updatedAt='" + getUpdatedAt() + "'" +
            "}";
    }
}
```

</details>

Thanks in advance

**Comment by mp911de** [comment] 2022-03-28 07:08
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem. Please also provide which database you're using.

**Comment by spring-projects-issues** [comment] 2022-04-04 07:12
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-04-11 07:12
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-04-11 07:12 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
