### ISSUE TITLE
update entity with ReactiveAuditorAware not working

### ISSUE THREAD

**Issue by nedphae** [spring-projects/spring-data-r2dbc#639] opened 2021-08-18 11:03 UTC
Versions:
    Spring boot 2.4.5.RELEASE
    spring-data-r2dbc 1.2.3.RELEASE
    r2dbc-postgresql 0.8.7.RELEASE

entity define:

```kotlin
class AuditingEntity  {

    var id: Long?

    @CreatedBy
    @Column("created_by")
    @JsonIgnore
    var createdBy: String? = null

    @CreatedDate
    @Column("created_date")
    @JsonIgnore
    var createdDate: Instant = Instant.now()

    @LastModifiedBy
    @Column("last_modified_by")
    @JsonIgnore
    var lastModifiedBy: String? = null

    @LastModifiedDate
    @Column("last_modified_date")
    @JsonIgnore
    var lastModifiedDate: Instant = Instant.now()

}
```

Repository:

```kotlin
interface AuditingEntityRepository : ReactiveSortingRepository<AuditingEntity , Long> 
```

ReactiveAuditorAware (this return a userName):

```kotlin
@Component
class SpringSecurityAuditorAware : ReactiveAuditorAware<String> {

    override fun getCurrentAuditor(): Mono<String> {
       return getCurrentUserLogin()
  }
}
```

it work well when insert a new entity, but when update an entity, this createdBy will be set to null, Is this correct? or it should not update createdBy  and createdDate.

**Comment by mp911de** [comment] 2021-09-01 12:18
Created fields should not be touched when saving a modified entity. Can you provide a reproducer for the mentioned issue?

**Comment by spring-projects-issues** [comment] 2021-09-08 12:18
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-09-15 12:18
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-09-15 12:18 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
