### ISSUE TITLE
Columns named as H2 keywords didn't read during queries

### ISSUE THREAD

**Issue by ks-zealot** [spring-projects/spring-data-r2dbc#800] opened 2022-11-17 11:39 UTC
Description:
Entities with column, named as H2 keywords correctly saves, but query returns this entity with null instead of column value.

Steps to reproduce:

1) Create two almost identical  entity

```
@Data
@Accessors(chain = true)
@Table(value = "Test_Entity")
public    class TestEntity {
    @Id
    Long id;

    @Column(value = "name")
    String name;

    @Column(value = "`month`")
    LocalDate month;

    @Column(value = "`year`")
    LocalDate year;
}


@Data
@Accessors(chain = true)
@Table(value = "Test_Entity1")
public    class TestEntity1 {
    @Id
    Long id;

    @Column(value = "name")
    String name;

    @Column(value = "_month_")
    LocalDate month;


    @Column(value = "_year_")
    LocalDate year;
}

```

2) Create repositories

```
public interface ReactiveTestEntityRepository extends ReactiveCrudRepository<TestEntity, Long> {
        Mono<TestEntity> findByName(String name);
}

public interface ReactiveTestEntity1Repository extends ReactiveCrudRepository<TestEntity1, Long> {

        Mono<TestEntity1> findByName(String name);
}
```

3) Write test

```
@Slf4j
@DataR2dbcTest
public class Test1 {

@Autowired
DatabaseClient databaseClient;

@Autowired
ReactiveTestEntityRepository repository;

@Autowired
ReactiveTestEntity1Repository repository1;

@Test
public void test() {
databaseClient.sql(
"CREATE table Test_Entity (id INT AUTO_INCREMENT NOT NULL, name VARCHAR2, `month` date, `year` date);")
.then().as(StepVerifier::create).verifyComplete();
Mono<TestEntity> testEntity = repository
.save(new TestEntity().setName("test").setMonth(LocalDate.now()).setYear(LocalDate.now()));
StepVerifier.create(testEntity)
.expectNext(
new TestEntity().setId(1l).setName("test").setYear(LocalDate.now()).setMonth(LocalDate.now()))
.expectComplete().verify();
Mono<TestEntity> testEntity1 = repository.findByName("test");
StepVerifier.create(testEntity1).expectNext(new TestEntity().setId(1l).setName("test").setYear(LocalDate.now())
.setMonth(LocalDate.now()).setYear(LocalDate.now())).expectComplete().verify();
}

@Test
public void test1() {
databaseClient.sql(
"CREATE table Test_Entity1 (id INT AUTO_INCREMENT NOT NULL, name VARCHAR2, _month_ date, _year_ date);")
.then().as(StepVerifier::create).verifyComplete();
Mono<TestEntity1> testEntity = repository1
.save(new TestEntity1().setName("test").setMonth(LocalDate.now()).setYear(LocalDate.now()));
StepVerifier.create(testEntity)
.expectNext(
new TestEntity1().setId(1l).setName("test").setYear(LocalDate.now()).setMonth(LocalDate.now()))
.expectComplete().verify();
Mono<TestEntity1> testEntity1 = repository1.findByName("test");
StepVerifier.create(testEntity1).expectNext(new TestEntity1().setId(1l).setName("test")
.setMonth(LocalDate.now()).setMonth(LocalDate.now()).setYear(LocalDate.now())).expectComplete()
.verify();
}
}

```
Expectation:
Both tests run without errors

Reality:
First test fails with assertion error

```
java.lang.AssertionError: expectation "expectNext(TestEntity(id=1, name=test, month=2022-11-17, year=2022-11-17))" failed (expected value: TestEntity(id=1, name=test, month=2022-11-17, year=2022-11-17); actual value: TestEntity(id=1, name=test, month=null, year=null))
```

So, if I name the column as 'month' and 'year', they did not properly read from db, even if I escape those names. Entity with underscore in column names works fine.
I suppose other H2 keywords are affected too.

Environment

Java: version 12
JUnit: 5.9.1
Spring Boot : 2.7.4
Spring Data R2DBC: 1.5.5
r2dbc-h2: 0.9.0.RELEASE
Reactor Test: 3.5.0

**Comment by mp911de** [comment] 2022-11-17 13:22
Have you tried enabling force quote on the `MappingContext`?

**Comment by ks-zealot** [comment] 2022-11-17 13:42
Yes
```
@Bean
	public R2dbcMappingContext r2dbcMappingContext(Optional<NamingStrategy> namingStrategy,
			R2dbcCustomConversions r2dbcCustomConversions) {

		Assert.notNull(namingStrategy, "NamingStrategy must not be null!");

		R2dbcMappingContext context = new R2dbcMappingContext();
		context.setForceQuote(true);

		return context;
	}
```

This code translate table name to upper case for some reason
```

java.lang.AssertionError: expectation "expectNext(TestEntity(id=1, name=test, month=2022-11-17, year=2022-11-17))" failed (expected: onNext(TestEntity(id=1, name=test, month=2022-11-17, year=2022-11-17)); actual: onError(org.springframework.r2dbc.BadSqlGrammarException: executeMany; bad SQL grammar [INSERT INTO "Test_Entity" ("name", "`month`", "`year`") VALUES ($1, $2, $3)]; nested exception is io.r2dbc.spi.R2dbcBadGrammarException: [42103] [42S03] Table "Test_Entity" not found (candidates are: "TEST_ENTITY"); SQL statement:
INSERT INTO "Test_Entity" ("name", "`month`", "`year`") VALUES ($1, $2, $3) [42103-206]))
```

**Comment by mp911de** [comment] 2022-11-17 15:18
Quoting often times comes with case-sensitivity. That can be tweaked through the dialect, see `IdentifierProcessing`.

**Comment by ks-zealot** [comment] 2022-11-17 17:51
Test now pass if I translate all column names to upper case:
```
@Data
@Accessors(chain = true)
@Table(value = "TEST_ENTITY")
public class TestEntity {
@Id
    @Column("ID")
Long id;

    @Column("NAME")
String name;

    @Column("MONTH")
LocalDate month;
    @Column("YEAR")
LocalDate year;
}
```
Tweaking H2 Dialect did not affect case sensitivity
```
@Bean
public R2dbcMappingContext r2dbcMappingContext() {


R2dbcMappingContext context = new R2dbcMappingContext();
context.setForceQuote(true);

return context;
}


@Bean
public Dialect h2Dialect( ) {
return new H2Dialect(){
@Override
public IdentifierProcessing getIdentifierProcessing() {
return IdentifierProcessing.create(new IdentifierProcessing.Quoting("\""),
IdentifierProcessing.LetterCasing.LOWER_CASE);
}
};
}

```

I suppose, setting letter casing to lower case should have broken the test with upper case column names, but it didn't.
But, if I translate column names to lower case and keep IdentifierProcessing letter casing in lowercase, the test broke with exception "column "name" not found".

**Comment by mp911de** [comment] 2022-12-12 13:52
Closing as the issue is solved and nothing actionable is left.

**Closed as not planned by mp911de** 2022-12-12 13:52 UTC
Labels: status: invalid
