### ISSUE TITLE
Reactive repository save method returns mono empty instead of mono value

### ISSUE THREAD

**Issue by baimurzin** [spring-projects/spring-data-r2dbc#67] opened 2019-02-26 17:44 UTC
I use 
`MyRepository implements R2dbcRepository<T, ID>`

I used method save from there and expect that it will return _Mono<Entity>_ but I got Empty.

`myRepositoryBean.save(myEntity)`

My dependencies: 

```
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-r2dbc</artifactId>
            <version>1.0.0.M1</version>
        </dependency>

        <dependency>
            <groupId>io.r2dbc</groupId>
            <artifactId>r2dbc-h2</artifactId>
            <version>1.0.0.BUILD-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.r2dbc</groupId>
            <artifactId>r2dbc-spi</artifactId>
            <version>1.0.0.M7</version>
        </dependency>
```

**Comment by mp911de** [comment] 2019-02-26 18:16
Sounds like a incompatibility right now. Switch R2DBC dependencies to 1.0.0.M7 and Spring Data R2DBC to 1.0.0.BUILD-SNAPSHOT. We have a lot of moving parts here.

**Comment by nbenjamin** [comment] 2019-03-06 14:42
@baimurzin  I tested with`<spring-data-r2dbc.version>1.0.0.M1</spring-data-r2dbc.version>` and `<r2dbc.version>1.0.0.M7</r2dbc.version>` and its working fine.
Here is the [example](https://github.com/nbenjamin/spring-data-r2dbc-examples/tree/master/r2dbc-postgresql-example)

**Comment by mp911de** [comment] 2019-03-07 06:13
Closing this ticket as things work as designed.

**Closed by mp911de** 2019-03-07 06:13 UTC
Labels: status: waiting-for-feedback

**Comment by Numbernick** [comment] 2019-03-27 14:16
For reference: I got the same problem as @baimurzin. Everything is fine with Postgres. It seems to be a problem with H2. I opened a ticket over there a week ago: https://github.com/r2dbc/r2dbc-h2/issues/61
