### ISSUE TITLE
Issue with inline fun <reified T : Any> DatabaseClient.BindSpec<*>.bind(name: String, value: T?)

### ISSUE THREAD

**Issue by vlipovetskii** [spring-projects/spring-data-r2dbc#222] opened 2019-10-22 16:11 UTC
.execute("SELECT ...")
.bind<String>("@username", null)
.map {...}
...

PRB: Unresolved reference.
None of the following candidates is applicable because of receiver type mismatch.

WO: 
.execute("SELECT ...")
.run { bind<String>("@username", username) as DatabaseClient.GenericExecuteSpec }
.map {...}

Permanent fix: 
Define explicitly function return type: 
**as DatabaseClient.GenericExecuteSpec** 
instead of inferred 
**DatabaseClient.BindSpec<*>**

inline fun <reified T : Any> DatabaseClient.BindSpec<*>.bind(name: String, value: T?) = bind(name, SettableValue.fromOrEmpty(value, T::class.java)) **as DatabaseClient.GenericExecuteSpec**

**Comment by mp911de** [comment] 2019-10-22 17:16
Duplicate of #209.

**Closed** 2019-10-22 17:17 UTC
Labels: status: duplicate
